/** Default categories, preset habits, challenge pool, subscription catalog. */
import type { Category, Plan } from "./store";

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: "morning",
    nameFa: "صبحگاهی",
    nameEn: "Morning",
    color: "#F59E0B",
    icon: "sunrise",
    isDefault: true,
  },
  {
    id: "health",
    nameFa: "سلامتی",
    nameEn: "Health",
    color: "#10B981",
    icon: "heart",
    isDefault: true,
  },
  {
    id: "sport",
    nameFa: "ورزش",
    nameEn: "Sport",
    color: "#EF4444",
    icon: "dumbbell",
    isDefault: true,
  },
  {
    id: "daily",
    nameFa: "روزمره",
    nameEn: "Daily",
    color: "#3B82F6",
    icon: "calendar",
    isDefault: true,
  },
  {
    id: "order",
    nameFa: "نظم و پاکیزگی",
    nameEn: "Tidiness",
    color: "#06B6D4",
    icon: "sparkles",
    isDefault: true,
  },
  {
    id: "growth",
    nameFa: "توسعه فردی",
    nameEn: "Self Growth",
    color: "#8B5CF6",
    icon: "trending",
    isDefault: true,
  },
  {
    id: "finance",
    nameFa: "اقتصادی",
    nameEn: "Finance",
    color: "#22C55E",
    icon: "wallet",
    isDefault: true,
  },
  {
    id: "food",
    nameFa: "غذا",
    nameEn: "Food",
    color: "#F97316",
    icon: "utensils",
    isDefault: true,
  },
  { id: "sleep", nameFa: "خواب", nameEn: "Sleep", color: "#6366F1", icon: "moon", isDefault: true },
  {
    id: "study",
    nameFa: "درس و مطالعه",
    nameEn: "Study",
    color: "#0EA5E9",
    icon: "book",
    isDefault: true,
  },
  {
    id: "productive",
    nameFa: "پروداکتیو بودن",
    nameEn: "Productivity",
    color: "#EAB308",
    icon: "zap",
    isDefault: true,
  },
  { id: "fun", nameFa: "تفریح", nameEn: "Fun", color: "#EC4899", icon: "gamepad", isDefault: true },
  {
    id: "pet",
    nameFa: "حیوان خانگی",
    nameEn: "Pet",
    color: "#A16207",
    icon: "paw",
    isDefault: true,
  },
  {
    id: "faith",
    nameFa: "ایمان",
    nameEn: "Faith",
    color: "#14B8A6",
    icon: "star",
    isDefault: true,
  },
  {
    id: "family",
    nameFa: "خانواده",
    nameEn: "Family",
    color: "#DB2777",
    icon: "users",
    isDefault: true,
  },
  {
    id: "limits",
    nameFa: "محدودیت‌ها",
    nameEn: "Limits",
    color: "#64748B",
    icon: "ban",
    isDefault: true,
    isLimit: true,
  },
];

export interface PresetHabit {
  nameFa: string;
  nameEn: string;
  type: "binary" | "quantity";
  target: number;
  unitFa?: string;
  unitEn?: string;
}

export const PRESET_HABITS: Record<string, PresetHabit[]> = {
  morning: [
    { nameFa: "بیدار شدن قبل از ۷ صبح", nameEn: "Wake up before 7 AM", type: "binary", target: 1 },
    { nameFa: "مرتب کردن تخت‌خواب", nameEn: "Make the bed", type: "binary", target: 1 },
    {
      nameFa: "یک لیوان آب بعد از بیدار شدن",
      nameEn: "Glass of water after waking",
      type: "binary",
      target: 1,
    },
    {
      nameFa: "نور آفتاب صبحگاهی",
      nameEn: "Morning sunlight",
      type: "quantity",
      target: 10,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    {
      nameFa: "نرمش صبحگاهی",
      nameEn: "Morning stretch",
      type: "quantity",
      target: 5,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    {
      nameFa: "مرور برنامهٔ روز قبل از شروع کار",
      nameEn: "Review today's plan",
      type: "binary",
      target: 1,
    },
  ],
  health: [
    {
      nameFa: "نوشیدن ۸ لیوان آب",
      nameEn: "Drink 8 glasses of water",
      type: "quantity",
      target: 8,
      unitFa: "لیوان",
      unitEn: "glasses",
    },
    {
      nameFa: "مدیتیشن و تنفس عمیق",
      nameEn: "Meditation & deep breathing",
      type: "quantity",
      target: 10,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    { nameFa: "مصرف ویتامین و مکمل", nameEn: "Take vitamins", type: "binary", target: 1 },
    {
      nameFa: "۸۰۰۰ قدم پیاده‌روی",
      nameEn: "Walk 8,000 steps",
      type: "quantity",
      target: 8000,
      unitFa: "قدم",
      unitEn: "steps",
    },
    { nameFa: "مراقبت از پوست", nameEn: "Skincare routine", type: "binary", target: 1 },
    {
      nameFa: "نخوردن نوشابه و نوشیدنی شیرین",
      nameEn: "No sugary drinks",
      type: "binary",
      target: 1,
    },
  ],
  sport: [
    {
      nameFa: "۳۰ دقیقه ورزش",
      nameEn: "30 min workout",
      type: "quantity",
      target: 30,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    {
      nameFa: "شنا سوئدی",
      nameEn: "Push-ups",
      type: "quantity",
      target: 30,
      unitFa: "عدد",
      unitEn: "reps",
    },
    {
      nameFa: "اسکوات",
      nameEn: "Squats",
      type: "quantity",
      target: 30,
      unitFa: "عدد",
      unitEn: "reps",
    },
    {
      nameFa: "دراز و نشست",
      nameEn: "Sit-ups",
      type: "quantity",
      target: 30,
      unitFa: "عدد",
      unitEn: "reps",
    },
    {
      nameFa: "حرکات کششی",
      nameEn: "Stretching",
      type: "quantity",
      target: 10,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    {
      nameFa: "طناب زدن",
      nameEn: "Jump rope",
      type: "quantity",
      target: 10,
      unitFa: "دقیقه",
      unitEn: "min",
    },
  ],
  daily: [
    {
      nameFa: "برنامه‌ریزی فردا قبل از خواب",
      nameEn: "Plan tomorrow before bed",
      type: "binary",
      target: 1,
    },
    { nameFa: "نوشتن ۳ کار مهم روز", nameEn: "Write top 3 tasks", type: "binary", target: 1 },
    { nameFa: "قدم زدن بعد از شام", nameEn: "Evening walk", type: "binary", target: 1 },
    { nameFa: "آب دادن به گل و گیاه", nameEn: "Water the plants", type: "binary", target: 1 },
    {
      nameFa: "شستن ظرف‌ها بعد از شام",
      nameEn: "Do the dishes after dinner",
      type: "binary",
      target: 1,
    },
  ],
  order: [
    { nameFa: "مرتب کردن میز کار", nameEn: "Tidy the desk", type: "binary", target: 1 },
    {
      nameFa: "۱۵ دقیقه نظافت خانه",
      nameEn: "15 min house cleaning",
      type: "quantity",
      target: 15,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    { nameFa: "جمع کردن لباس‌ها سر جایشان", nameEn: "Put clothes away", type: "binary", target: 1 },
    {
      nameFa: "خالی کردن سینک قبل از خواب",
      nameEn: "Empty sink before bed",
      type: "binary",
      target: 1,
    },
    {
      nameFa: "مرتب کردن فایل‌ها و دسکتاپ",
      nameEn: "Organize digital files",
      type: "quantity",
      target: 10,
      unitFa: "دقیقه",
      unitEn: "min",
    },
  ],
  growth: [
    {
      nameFa: "مطالعهٔ کتاب",
      nameEn: "Read a book",
      type: "quantity",
      target: 20,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    {
      nameFa: "یادگیری مهارت جدید",
      nameEn: "Learn a new skill",
      type: "quantity",
      target: 30,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    { nameFa: "نوشتن ۳ مورد شکرگزاری", nameEn: "Write 3 gratitudes", type: "binary", target: 1 },
    {
      nameFa: "گوش دادن به پادکست آموزشی",
      nameEn: "Educational podcast",
      type: "quantity",
      target: 20,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    {
      nameFa: "تمرین زبان خارجی",
      nameEn: "Language practice",
      type: "quantity",
      target: 15,
      unitFa: "دقیقه",
      unitEn: "min",
    },
  ],
  finance: [
    { nameFa: "ثبت هزینه‌های روز", nameEn: "Track daily expenses", type: "binary", target: 1 },
    { nameFa: "پس‌انداز روزانه", nameEn: "Daily saving", type: "binary", target: 1 },
    {
      nameFa: "خرید نکردن چیزهای غیرضروری",
      nameEn: "No impulse buying",
      type: "binary",
      target: 1,
    },
    {
      nameFa: "مرور وضعیت مالی",
      nameEn: "Review finances",
      type: "quantity",
      target: 10,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    {
      nameFa: "یادگیری دربارهٔ سرمایه‌گذاری",
      nameEn: "Learn about investing",
      type: "quantity",
      target: 15,
      unitFa: "دقیقه",
      unitEn: "min",
    },
  ],
  food: [
    { nameFa: "خوردن صبحانهٔ سالم", nameEn: "Healthy breakfast", type: "binary", target: 1 },
    {
      nameFa: "میوه و سبزیجات",
      nameEn: "Fruits & veggies",
      type: "quantity",
      target: 3,
      unitFa: "وعده",
      unitEn: "servings",
    },
    { nameFa: "آشپزی در خانه", nameEn: "Home-cooked meal", type: "binary", target: 1 },
    { nameFa: "نخوردن قند و شیرینی", nameEn: "No sugar & sweets", type: "binary", target: 1 },
    { nameFa: "وعده‌های غذایی سر وقت", nameEn: "Eat meals on time", type: "binary", target: 1 },
  ],
  sleep: [
    { nameFa: "خواب قبل از ۱۲ شب", nameEn: "Sleep before midnight", type: "binary", target: 1 },
    {
      nameFa: "۸ ساعت خواب",
      nameEn: "8 hours of sleep",
      type: "quantity",
      target: 8,
      unitFa: "ساعت",
      unitEn: "hours",
    },
    {
      nameFa: "کنار گذاشتن موبایل ۱ ساعت قبل خواب",
      nameEn: "No phone 1h before bed",
      type: "binary",
      target: 1,
    },
    { nameFa: "بیدار شدن سر ساعت مشخص", nameEn: "Wake at a fixed time", type: "binary", target: 1 },
    {
      nameFa: "چرت کوتاه روزانه",
      nameEn: "Power nap",
      type: "quantity",
      target: 20,
      unitFa: "دقیقه",
      unitEn: "min",
    },
  ],
  study: [
    {
      nameFa: "مطالعهٔ درسی",
      nameEn: "Study session",
      type: "quantity",
      target: 60,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    { nameFa: "مرور فلش‌کارت", nameEn: "Review flashcards", type: "binary", target: 1 },
    {
      nameFa: "حل تمرین و تست",
      nameEn: "Practice problems",
      type: "quantity",
      target: 20,
      unitFa: "تست",
      unitEn: "problems",
    },
    {
      nameFa: "مرور جزوه‌های امروز",
      nameEn: "Review today's notes",
      type: "quantity",
      target: 15,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    {
      nameFa: "مطالعه بدون موبایل",
      nameEn: "Phone-free study",
      type: "quantity",
      target: 45,
      unitFa: "دقیقه",
      unitEn: "min",
    },
  ],
  productive: [
    {
      nameFa: "کار عمیق بدون حواس‌پرتی",
      nameEn: "Deep work",
      type: "quantity",
      target: 90,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    { nameFa: "اولویت‌بندی ۳ کار مهم", nameEn: "Top 3 priorities", type: "binary", target: 1 },
    {
      nameFa: "تکنیک پومودورو",
      nameEn: "Pomodoro sessions",
      type: "quantity",
      target: 4,
      unitFa: "جلسه",
      unitEn: "sessions",
    },
    { nameFa: "یادداشت کردن ایده‌ها", nameEn: "Capture ideas", type: "binary", target: 1 },
    {
      nameFa: "بدون شبکهٔ اجتماعی در ساعت کاری",
      nameEn: "No social media at work",
      type: "binary",
      target: 1,
    },
  ],
  fun: [
    {
      nameFa: "وقت گذاشتن برای سرگرمی موردعلاقه",
      nameEn: "Hobby time",
      type: "quantity",
      target: 30,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    {
      nameFa: "گوش دادن به موسیقی",
      nameEn: "Music time",
      type: "quantity",
      target: 20,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    {
      nameFa: "بازی کردن",
      nameEn: "Gaming time",
      type: "quantity",
      target: 30,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    { nameFa: "تماشای فیلم یا سریال", nameEn: "Movie or series", type: "binary", target: 1 },
    {
      nameFa: "نقاشی یا کاردستی",
      nameEn: "Draw or craft",
      type: "quantity",
      target: 20,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    { nameFa: "وقت گذراندن با دوستان", nameEn: "Hang out with friends", type: "binary", target: 1 },
  ],
  pet: [
    { nameFa: "قدم زدن با حیوان خانگی", nameEn: "Walk the pet", type: "binary", target: 1 },
    {
      nameFa: "بازی با حیوان خانگی",
      nameEn: "Play with pet",
      type: "quantity",
      target: 15,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    { nameFa: "غذا و آب تازه", nameEn: "Fresh food & water", type: "binary", target: 1 },
    { nameFa: "تمیز کردن ظرف و جای خواب", nameEn: "Clean bowls & bed", type: "binary", target: 1 },
    { nameFa: "برس کشیدن حیوان خانگی", nameEn: "Brush the pet", type: "binary", target: 1 },
  ],
  faith: [
    { nameFa: "عبادت روزانه", nameEn: "Daily prayer", type: "binary", target: 1 },
    {
      nameFa: "خواندن قرآن یا متن معنوی",
      nameEn: "Read scripture",
      type: "quantity",
      target: 10,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    {
      nameFa: "ذکر و مراقبه",
      nameEn: "Dhikr & reflection",
      type: "quantity",
      target: 10,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    { nameFa: "شکرگزاری شبانه", nameEn: "Nightly gratitude", type: "binary", target: 1 },
    { nameFa: "صدقه یا کار خیر", nameEn: "Charity or good deed", type: "binary", target: 1 },
  ],
  family: [
    { nameFa: "تماس با پدر و مادر", nameEn: "Call parents", type: "binary", target: 1 },
    {
      nameFa: "وقت باکیفیت با خانواده",
      nameEn: "Quality family time",
      type: "quantity",
      target: 30,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    {
      nameFa: "بازی با بچه‌ها",
      nameEn: "Play with the kids",
      type: "quantity",
      target: 20,
      unitFa: "دقیقه",
      unitEn: "min",
    },
    { nameFa: "شام دور هم", nameEn: "Dinner together", type: "binary", target: 1 },
    { nameFa: "کمک در کارهای خانه", nameEn: "Help with housework", type: "binary", target: 1 },
  ],
  limits: [
    { nameFa: "سیگار نکشیدن", nameEn: "No smoking", type: "binary", target: 1 },
    {
      nameFa: "کمتر از ۱ ساعت شبکهٔ اجتماعی",
      nameEn: "Under 1h social media",
      type: "binary",
      target: 1,
    },
    { nameFa: "نخوردن فست‌فود", nameEn: "No fast food", type: "binary", target: 1 },
    {
      nameFa: "بدون کافئین بعد از عصر",
      nameEn: "No caffeine after 5 PM",
      type: "binary",
      target: 1,
    },
    { nameFa: "بدون گوشی سر میز غذا", nameEn: "No phone at meals", type: "binary", target: 1 },
    { nameFa: "غر نزدن و شکایت نکردن", nameEn: "No complaining", type: "binary", target: 1 },
  ],
};

/* ---------------- subscription catalog ----------------
 * Static for now. These become server-authoritative (GET /v1/plans) once the
 * backend lands; the client will never author them. Until then they are read-only
 * constants rather than user-editable DB state. */

export const PLANS: Plan[] = [
  { id: "m1", nameFa: "یک‌ماهه", nameEn: "1 Month", months: 1, price: 59000 },
  { id: "m3", nameFa: "سه‌ماهه", nameEn: "3 Months", months: 3, price: 149000 },
  { id: "m12", nameFa: "یک‌ساله", nameEn: "1 Year", months: 12, price: 449000 },
];

export const CATEGORY_COLOR_CHOICES = [
  "#F97316",
  "#EF4444",
  "#F59E0B",
  "#EAB308",
  "#84CC16",
  "#22C55E",
  "#10B981",
  "#14B8A6",
  "#06B6D4",
  "#0EA5E9",
  "#3B82F6",
  "#6366F1",
  "#8B5CF6",
  "#A855F7",
  "#D946EF",
  "#EC4899",
  "#DB2777",
  "#A16207",
  "#78716C",
  "#64748B",
];

export const MOOD_EMOJIS = ["😄", "🙂", "😐", "😔", "😫", "😡", "🤩", "😴", "💪", "❤️"];
