export interface GuideStep {
  id: string;
  title: [string, string];
  body: [string, string];
}
const s = (id: string, fa: string, en: string, bodyFa: string, bodyEn: string): GuideStep => ({
  id,
  title: [fa, en],
  body: [bodyFa, bodyEn],
});

export const GUIDE_SECTIONS = {
  today: [
    s(
      "intro",
      "روز تو در یک نگاه",
      "Your day at a glance",
      "اینجا نمای روز توست؛ عادت‌ها و کارهای روز انتخاب‌شده را یک‌جا می‌بینی.",
      "See the habits and tasks for your selected day in one place.",
    ),
    s(
      "date",
      "انتخاب روز",
      "Choose a day",
      "از این نوار روز را انتخاب کن تا برنامه و ثبت‌های همان روز را ببینی.",
      "Choose a day here to see its plan and recorded progress.",
    ),
    s(
      "habits",
      "ثبت عادت‌ها",
      "Record your habits",
      "انجام عادت‌ها را همین‌جا ثبت کن. برای عادت‌های مقداری، مقدار انجام‌شده را وارد کن.",
      "Mark habits done here. For quantity habits, enter the amount you completed.",
    ),
    s(
      "tasks",
      "کارهای روز",
      "Daily tasks",
      "کارت کارها را باز کن تا کارهای این روز را ببینی و انجام‌شده‌ها را علامت بزنی.",
      "Open the task card to see this day's tasks and mark them done.",
    ),
    s(
      "navigation",
      "بخش‌های روتینو",
      "Find your way",
      "از نوار پایین بین بخش‌ها جابه‌جا شو. بالای صفحه هم به تنظیمات و اعلان‌ها دسترسی داری.",
      "Use the bottom bar to switch sections. Settings and notifications are at the top.",
    ),
  ],
  goals: [
    s(
      "intro",
      "هدف‌ها، قدم به قدم",
      "Goals, step by step",
      "اینجا هدف‌های مهمت را به قدم‌های کوچک‌تر تبدیل کن و پیشرفتشان را دنبال کن.",
      "Break your important goals into smaller steps and follow their progress here.",
    ),
    s(
      "create",
      "ساخت هدف",
      "Create a goal",
      "با «هدف جدید» عنوان هدفت را بنویس؛ دسته‌بندی، اولویت و مهلت را هم اگر خواستی مشخص کن.",
      "Use New goal to give your goal a title. Category, priority and deadline are optional.",
    ),
    s(
      "summary",
      "پیشرفت در یک نگاه",
      "Progress at a glance",
      "این کارت پیشرفت کلی و تعداد هدف‌های فعال، انجام‌شده و عقب‌افتاده را نشان می‌دهد.",
      "This card shows overall progress and counts of active, completed and overdue goals.",
    ),
    s(
      "filters",
      "پیدا کردن هدف‌ها",
      "Find your goals",
      "با این فیلترها همهٔ هدف‌ها یا فقط هدف‌های فعال، انجام‌شده و عقب‌افتاده را ببین.",
      "Use these filters to see all goals or just active, completed or overdue ones.",
    ),
    s(
      "list",
      "قدم‌های هر هدف",
      "Steps for each goal",
      "هر هدف را باز کن تا عادت، کار یا آیتم دلخواه به آن اضافه کنی؛ پیشرفت قدم‌ها را همان‌جا دنبال کن.",
      "Open a goal to add habits, tasks or custom items, then follow each step's progress there.",
    ),
  ],
  habits: [
    s(
      "intro",
      "قدم‌های کوچک، هر روز",
      "Small steps, every day",
      "عادت‌ها کارهایی‌اند که می‌خواهی مرتب تکرارشان کنی؛ مثل مطالعه یا ورزش.",
      "Habits are things you want to repeat regularly, like reading or exercise.",
    ),
    s(
      "create",
      "ساختن عادت",
      "Create a habit",
      "از عادت‌های آماده انتخاب کن یا با «عادت دلخواه» عادت خودت را بساز.",
      "Choose a preset or create your own with Custom habit.",
    ),
    s(
      "filters",
      "پیدا کردن عادت‌ها",
      "Find your habits",
      "با فیلترها، عادت‌های هر دسته یا انجام‌شده و انجام‌نشده‌ها را پیدا کن.",
      "Filter by category or by completed and incomplete habits.",
    ),
    s(
      "progress",
      "پیشرفت و نشان‌ها",
      "Progress and badges",
      "جزئیات هر عادت پیشرفتت را نشان می‌دهد؛ با رسیدن به هدف ماهانه، نشانش را می‌گیری.",
      "Habit details show your progress. Reaching a monthly goal earns a badge.",
    ),
  ],
  tasks: [
    s(
      "intro",
      "کارهای مشخصت",
      "Things to get done",
      "اینجا کارهای مشخصت را برنامه‌ریزی کن؛ مثل آماده‌کردن گزارش یا خرید.",
      "Plan specific tasks here, like preparing a report or shopping.",
    ),
    s(
      "date",
      "انتخاب تاریخ",
      "Pick a date",
      "امروز، فردا یا یک تاریخ دلخواه را انتخاب کن تا کارهای همان روز را ببینی.",
      "Choose today, tomorrow or another date to see its tasks.",
    ),
    s(
      "create",
      "افزودن کار",
      "Add a task",
      "با «افزودن کار»، عنوان و جزئیات کار را مشخص کن؛ یادآور و ددلاین اختیاری‌اند.",
      "Use Add task to set its title and details. Reminders and deadlines are optional.",
    ),
    s(
      "list",
      "ثبت انجام کار",
      "Record completion",
      "بعد از انجام کار علامتش بزن؛ برای کارهای مقداری، مقدار انجام‌شده را ثبت کن.",
      "Mark a task done when you finish. For quantity tasks, record the amount completed.",
    ),
  ],
  timer: [
    s(
      "modes",
      "زمانت را مدیریت کن",
      "Manage your time",
      "برای زمان گرفتن، پومودورو، تایمر آزاد یا کرونومتر را انتخاب کن.",
      "Choose Pomodoro, a free timer or a stopwatch to track time.",
    ),
    s(
      "pomodoro",
      "تمرکز و استراحت",
      "Focus and rest",
      "پومودورو زمان تمرکز و استراحت را نوبتی اجرا می‌کند؛ مدت‌ها و تعداد دورها را خودت تنظیم کن.",
      "Pomodoro alternates focus and rest. Set the durations and number of rounds.",
    ),
    s(
      "clock",
      "تایمر آزاد و کرونومتر",
      "Free timer and stopwatch",
      "در تایمر آزاد، زمان مشخص کن؛ کرونومتر زمان سپری‌شده را می‌شمارد.",
      "A free timer counts down a duration; the stopwatch measures elapsed time.",
    ),
    s(
      "link",
      "اتصال به عادت یا کار",
      "Link a habit or task",
      "تایمر را به یک عادت، کار یا آیتم زمانیِ هدف وصل کن تا زمان تمرکز برای همان مورد ثبت شود.",
      "Link a time-based habit, task or Goal item to record focus time for it.",
    ),
    s(
      "controls",
      "شروع و توقف",
      "Start and pause",
      "از کنترل‌های تایمر شروع، توقف موقت یا شروع دوباره را انجام بده؛ جلسات اخیر پایین صفحه‌اند.",
      "Use these controls to start, pause or reset. Recent sessions appear below.",
    ),
  ],
  journal: [
    s(
      "intro",
      "چند لحظه برای خودت",
      "A moment for yourself",
      "اینجا چند لحظه برای مرور روزت وقت بگذار؛ لازم نیست یادداشتت طولانی باشد.",
      "Take a moment to reflect on your day. A short note is enough.",
    ),
    s(
      "mood",
      "حال و احساس",
      "Your mood",
      "روز موردنظر را انتخاب کن و حال و احساست را ثبت کن.",
      "Choose a day and record how you felt.",
    ),
    s(
      "note",
      "مرور روز",
      "Reflect on your day",
      "به روزت نمره بده و اگر خواستی، دربارهٔ اتفاق‌ها یا فکرهایت بنویس.",
      "Rate your day and optionally write about what happened or what was on your mind.",
    ),
    s(
      "save",
      "ذخیرهٔ ژورنال",
      "Save your journal",
      "برای ثبت تغییرات «ذخیره» را بزن؛ یادداشت‌های اخیرت پایین صفحه‌اند.",
      "Press Save to record your changes. Recent entries appear below.",
    ),
  ],
  "analytics-habits": [
    s(
      "weekly",
      "مرور هفتگی",
      "Weekly review",
      "مرور هفتگی کمک می‌کند پیشرفت و جاافتادگی‌ها را ببینی.",
      "The weekly review helps you spot progress and missed habits.",
    ),
    s(
      "overall",
      "روند عادت‌ها",
      "Habit trends",
      "در عملکرد کلی، بازه را عوض کن تا روند انجام عادت‌ها را مقایسه کنی.",
      "Change the overall performance range to compare your habit trends.",
    ),
    s(
      "individual",
      "عملکرد هر عادت",
      "Each habit's performance",
      "در عملکرد هر عادت، وضعیت همان عادت را در ماه انتخاب‌شده بررسی کن.",
      "Review each habit's performance in the selected month. Switch to Tasks for task statistics.",
    ),
  ],
  "analytics-tasks": [
    s(
      "overall",
      "عملکرد کارها",
      "Task performance",
      "عملکرد کارها جدا از عادت‌ها نمایش داده می‌شود؛ بازه را عوض کن تا روند انجام کارها را مقایسه کنی.",
      "Tasks are shown separately from habits. Change the range to compare completion trends.",
    ),
    s(
      "list",
      "وضعیت کارهای ماه",
      "This month's tasks",
      "اینجا کارهای انجام‌شده، انجام‌نشده و به‌تعویق‌افتادهٔ ماه را می‌بینی.",
      "See the month's completed, pending and overdue tasks here.",
    ),
  ],
  settings: [
    s(
      "account",
      "حساب و اشتراک",
      "Account and subscription",
      "اطلاعات حساب، وضعیت اشتراک و تنظیم نام کاربری و رمز عبور اینجاست.",
      "Find account details, subscription status, and username and password settings here.",
    ),
    s(
      "appearance",
      "روتینو به سلیقهٔ تو",
      "Make Routino yours",
      "زبان، تقویم، تم و رنگ روتینو را مطابق سلیقه‌ات تنظیم کن.",
      "Choose your language, calendar, theme and brand color.",
    ),
    s(
      "categories",
      "مرتب‌کردن عادت‌ها",
      "Organize your habits",
      "دسته‌بندی‌ها کمک می‌کنند عادت‌هایت را مرتب نگه داری.",
      "Categories help keep your habits organized.",
    ),
    s(
      "notifications",
      "اعلان‌ها و یادآورها",
      "Notifications and reminders",
      "اعلان‌ها، صدای تکمیل، بازخورد لمسی و یادآوری ژورنال را اینجا تنظیم کن.",
      "Set up notifications, completion sounds, haptics and journal reminders here.",
    ),
    s(
      "help",
      "راهنما و ارتباط",
      "Help and feedback",
      "از این قسمت راهنما را دوباره شروع کن، نظرت را بفرست یا قوانین و راه‌های تماس را ببین.",
      "Restart the guide, send feedback, or read the terms and contact details.",
    ),
  ],
  "habit-form": [
    s(
      "name",
      "نام و دسته",
      "Name and category",
      "یک نام روشن برای عادتت بنویس و دسته‌اش را انتخاب کن؛ مثلاً مطالعه در دستهٔ رشد فردی.",
      "Give your habit a clear name and choose a category, like reading under personal growth.",
    ),
    s(
      "measurement",
      "روش ثبت و هدف",
      "Measurement and target",
      "برای ثبت ساده «انجام شد / نشد» را انتخاب کن؛ برای ثبت تعداد یا مدت، از «مقداری» استفاده کن.",
      "Choose Done / not done for a simple check, or Quantity to record a count or duration.",
    ),
    s(
      "repeat",
      "روزهای تکرار",
      "Repeat days",
      "روزهایی را انتخاب کن که می‌خواهی این عادت را انجام بدهی؛ حداقل یک روز لازم است.",
      "Choose the weekdays for this habit. Select at least one day.",
    ),
    s(
      "monthly",
      "هدف ماهانه",
      "Monthly goal",
      "مشخص کن در ماه چند روز می‌خواهی این عادت را کامل انجام بدهی؛ مثلاً ۲۰ روز.",
      "Set how many days you want to complete this habit each month, for example 20.",
    ),
    s(
      "save",
      "یادآور و ذخیره",
      "Reminders and saving",
      "یادآور و ددلاین روزانه اختیاری‌اند. بعد از تنظیم جزئیات، عادتت را ذخیره کن.",
      "A daily reminder and deadline are optional. Save your habit when you're ready.",
    ),
  ],
  "task-form": [
    s(
      "name",
      "عنوان و تاریخ",
      "Title and date",
      "عنوان کار و روز انجامش را مشخص کن؛ مثلاً آماده‌کردن گزارش برای فردا.",
      "Set a title and date, like preparing a report tomorrow.",
    ),
    s(
      "measurement",
      "نوع سنجش",
      "Measurement",
      "ثبت ساده یا مقدار انجام‌شده را انتخاب کن؛ کارهای زمانی هم می‌توانند به تایمر وصل شوند.",
      "Choose a simple check or a quantity. Time-based tasks can also link to the timer.",
    ),
    s(
      "target",
      "مقدار یا مدت هدف",
      "Amount or duration",
      "هدف را با واحد درست مشخص کن؛ مثلاً ۱۰ صفحه یا ۳۰ دقیقه.",
      "Set a target in the appropriate unit, such as 10 pages or 30 minutes.",
    ),
    s(
      "reminder",
      "یادآور و ددلاین",
      "Reminder and deadline",
      "یادآور زمان اطلاع‌دادن است؛ ددلاین مهلت انجام کار. هر دو اختیاری‌اند.",
      "A reminder tells you when to act; a deadline sets the due time. Both are optional.",
    ),
    s(
      "save",
      "ذخیرهٔ کار",
      "Save the task",
      "با ذخیره، کار به برنامهٔ روز انتخاب‌شده اضافه می‌شود.",
      "Saving adds this task to your selected day's plan.",
    ),
  ],
  "habit-detail": [
    s(
      "summary",
      "پیشرفت این عادت",
      "Habit progress",
      "خلاصهٔ عملکرد و پیوستگی این عادت را اینجا می‌بینی.",
      "See a summary of this habit's performance and consistency here.",
    ),
    s(
      "monthly",
      "هدف این ماه",
      "This month's goal",
      "این قسمت تعداد روزهای کامل‌شده را در برابر هدف ماهانه نشان می‌دهد.",
      "Compare completed days with your monthly goal here.",
    ),
    s(
      "chart",
      "روند در زمان",
      "Progress over time",
      "بازهٔ نمودار را تغییر بده تا روند این عادت را در زمان ببینی.",
      "Change the chart range to review this habit's trend over time.",
    ),
    s(
      "calendar",
      "تقویم ثبت‌ها",
      "Record calendar",
      "تقویم نشان می‌دهد در کدام روزها عادتت را کامل انجام داده‌ای.",
      "The calendar shows the days when you fully completed this habit.",
    ),
  ],
  presets: [
    s(
      "intro",
      "انتخاب عادت آماده",
      "Choose a preset",
      "یک دسته و عادت را انتخاب کن؛ قبل از اضافه‌کردن می‌توانی جزئیات و هدفش را تنظیم کنی.",
      "Choose a category and habit. Adjust its details and target before adding it.",
    ),
  ],
  "habit-log": [
    s(
      "intro",
      "ثبت انجام عادت",
      "Record your habit",
      "مقدار واقعی انجام‌شده را وارد کن؛ اگر خواستی، احساس و یک یادداشت کوتاه هم اضافه کن.",
      "Enter the amount you actually completed. Optionally add a mood and short note.",
    ),
  ],
  category: [
    s(
      "intro",
      "دستهٔ جدید",
      "New category",
      "برای دسته یک نام انتخاب کن؛ آیکون و رنگ کمک می‌کنند راحت‌تر پیدایش کنی.",
      "Give the category a name. An icon and color make it easier to find.",
    ),
  ],
  password: [
    s(
      "intro",
      "ورود با رمز عبور",
      "Password sign-in",
      "نام کاربری و رمز عبور را اینجا تنظیم کن تا بتوانی با آن‌ها هم وارد حساب شوی.",
      "Set a username and password here to use them for signing in too.",
    ),
  ],
} satisfies Record<string, GuideStep[]>;

export type GuideSection = keyof typeof GUIDE_SECTIONS;
export const HELP_TOPICS = {
  success: [
    "درصد موفقیت",
    "Success rate",
    "درصد روزهای برنامه‌ریزی‌شده‌ای که در بازهٔ انتخاب‌شده این عادت را کامل انجام داده‌ای.",
    "The percentage of scheduled days in the selected range when you fully completed this habit.",
  ],
  longest: [
    "بیشترین استریک",
    "Longest streak",
    "طولانی‌ترین زنجیرهٔ نوبت‌های پیوسته‌ای که تا امروز این عادت را کامل انجام داده‌ای.",
    "Your longest run of consecutive scheduled completions for this habit so far.",
  ],
  total: [
    "مجموع ثبت‌شده",
    "Recorded total",
    "مجموع مقدار یا زمانی که تا امروز برای این عادت ثبت کرده‌ای.",
    "The total amount or time recorded for this habit up to today.",
  ],
  sound: [
    "صدای تکمیل",
    "Completion sound",
    "بعد از ثبت موفق انجام یک عادت یا کار، یک صدای کوتاه پخش می‌شود.",
    "Play a short sound after successfully recording a habit or task completion.",
  ],
  haptics: [
    "بازخورد لمسی",
    "Haptic feedback",
    "روی گوشی‌های سازگار، هنگام بعضی تعامل‌ها یک لرزش کوتاه حس می‌کنی.",
    "On supported phones, some interactions give a short vibration.",
  ],
  target: [
    "مقدار هدف",
    "Target amount",
    "مقداری که می‌خواهی انجام بدهی؛ مثلاً ۱۰ صفحه مطالعه. برای هدف زمانی، مدت را مشخص کن.",
    "How much you want to complete, like 10 pages. For a time-based target, set a duration.",
  ],
  measurement: [
    "نوع سنجش",
    "Measurement",
    "«انجام شد / نشد» برای ثبت ساده است. «مقداری» برای ثبت تعداد یا مدت انجام کار است.",
    "Done / not done is a simple check. Quantity records a count or duration.",
  ],
  monthly: [
    "هدف ماهانه",
    "Monthly goal",
    "می‌خواهی در این ماه چند روز این عادت را کامل انجام بدهی؟ مثلاً ۲۰ روز؛ این عدد مقدار روزانه نیست.",
    "How many days do you want to complete this habit this month? For example 20 days, not the daily amount.",
  ],
  repeat: [
    "روزهای تکرار",
    "Repeat days",
    "روزهایی را انتخاب کن که می‌خواهی این عادت در برنامه‌ات باشد.",
    "Choose the weekdays when this habit should appear in your plan.",
  ],
  "habit-reminder": [
    "یادآور عادت",
    "Habit reminder",
    "در روزهای برنامهٔ این عادت، ساعت انتخاب‌شده یادآوری دریافت می‌کنی؛ اعلان‌ها و مجوز دستگاه باید فعال باشند.",
    "Get a reminder at the selected time on scheduled habit days. Notifications and device permission must be enabled.",
  ],
  "task-reminder": [
    "یادآور کار",
    "Task reminder",
    "در تاریخ این کار، ساعت انتخاب‌شده به تو یادآوری می‌شود؛ اعلان‌ها و مجوز دستگاه باید فعال باشند.",
    "Get a reminder at the selected time on this task's date. Notifications and device permission must be enabled.",
  ],
  "task-deadline": [
    "ددلاین",
    "Deadline",
    "مهلت انجام این کار است؛ یعنی تا این تاریخ و ساعت برای انجامش وقت داری.",
    "The due date and time for completing this task.",
  ],
  "habit-deadline": [
    "ددلاین روزانه",
    "Daily deadline",
    "مهلت ثبت انجام این عادت در هر روز است؛ بعد از این ساعت، ثبت انجام یا افزایش مقدار محدود می‌شود.",
    "The daily cut-off for recording completion. After this time, marking done or increasing the amount is restricted.",
  ],
  pomodoro: [
    "پومودورو",
    "Pomodoro",
    "یک روش تمرکز با استراحت‌های کوتاه است؛ مثلاً ۲۵ دقیقه تمرکز و ۵ دقیقه استراحت. زمان‌ها و تعداد دورها قابل تنظیم‌اند.",
    "A focus method with short breaks, such as 25 minutes of focus and 5 minutes of rest. Adjust the times and number of rounds.",
  ],
  link: [
    "اتصال تایمر",
    "Link timer",
    "یک عادت، کار یا آیتم زمانیِ مستقلِ هدف انتخاب کن؛ زمان تمرکز جلسه به همان مورد اضافه می‌شود.",
    "Choose a time-based habit, task or standalone Goal item. This session's focus time is added to it.",
  ],
  "journal-reminder": [
    "یادآوری ژورنال",
    "Journal reminder",
    "در ساعت انتخاب‌شده، یادآوری ثبت ژورنال دریافت می‌کنی؛ اعلان‌ها باید فعال باشند.",
    "Get a journal reminder at the selected time. Notifications must be enabled.",
  ],
  notifications: [
    "اعلان‌ها",
    "Notifications",
    "برای دریافت یادآورها، اعلان‌ها را فعال کن و اجازهٔ نمایش را در گوشی یا مرورگر بده.",
    "Enable notifications and allow them in your phone or browser to receive reminders.",
  ],
  progress: [
    "درصد پیشرفت",
    "Progress percentage",
    "درصد پیشرفت، مقدار انجام‌شده را نسبت به هدف نشان می‌دهد؛ جزئیات هر نمودار را از عنوان و بازه‌اش بخوان.",
    "Progress compares what you completed with your target. Check each chart's title and range for its context.",
  ],
  streak: [
    "پیوستگی",
    "Consistency",
    "تعداد نوبت‌های برنامه‌ریزی‌شده‌ای که پشت سر هم این عادت را کامل انجام داده‌ای.",
    "The number of consecutive scheduled occasions on which you completed this habit.",
  ],
  erase: [
    "پاک کردن داده‌ها",
    "Erase data",
    "این گزینه محتوای برنامه را پاک می‌کند؛ حذف حساب نیست. پیش از تأیید، متن هشدار را بخوان.",
    "This clears app content; it does not delete your account. Read the warning before confirming.",
  ],
  signout: [
    "خروج از حساب",
    "Sign out",
    "از حساب روی این دستگاه خارج می‌شوی؛ برای استفادهٔ دوباره باید وارد حساب شوی.",
    "Sign out on this device. You will need to sign in again to use your account.",
  ],
} satisfies Record<string, [string, string, string, string]>;
export type HelpTopic = keyof typeof HELP_TOPICS;
