-- Routino database setup for Supabase.
-- Generated by scripts/gen-setup-sql.mjs from backend/src/db/ddl.ts (the same
-- DDL the test suites run) plus Supabase-hosting-specific sections below.
-- Idempotent (if not exists / on conflict) — safe to run more than once.
-- Apply: paste into the Supabase SQL Editor, or DATABASE_URL=... node scripts/apply-db-setup.mjs

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  phone text not null unique,
  username text,
  password_hash text,
  seq bigint not null default 0,
  gc_seq bigint not null default 0,
  sync_record_count integer not null default 0,
  sync_data_bytes bigint not null default 0,
  constraint users_sync_record_count_bounds check
    (sync_record_count between 0 and 50000),
  constraint users_sync_data_bytes_bounds check
    (sync_data_bytes between 0 and 134217728),
  created_at timestamptz not null default now()
);
-- Pre-launch cleanup: these fields and tables are no longer part of the product.
drop table if exists device_security_events;
drop table if exists devices;
alter table users drop column if exists blocked;
alter table users drop column if exists max_active_devices;
alter table users drop column if exists security_locked_at;
alter table users drop column if exists security_lock_reason;
alter table users drop column if exists device_switch_reset_at;

create table if not exists records (
  user_id uuid not null references users(id) on delete cascade,
  kind text not null,
  id text not null,
  data jsonb,
  updated_at bigint not null,
  deleted boolean not null default false,
  seq bigint not null,
  primary key (user_id, kind, id),
  constraint records_kind_valid check (kind in
    ('categories','habits','habitMonths','tasks','timerSessions','journal'))
);
delete from records where kind = 'settings';
alter table records drop constraint if exists records_kind_valid;
alter table records add constraint records_kind_valid check (kind in
  ('categories','habits','habitMonths','tasks','timerSessions','journal'));
create index if not exists records_pull on records (user_id, seq);

-- Exact per-account storage accounting. Existing databases are backfilled only
-- while the trigger set is absent; normal boots see the triggers and skip the
-- aggregate scan entirely. Statement-level transition tables update each user
-- once per INSERT/UPDATE/DELETE statement, not once per record in a batch.
alter table users add column if not exists sync_record_count integer not null default 0;
alter table users add column if not exists sync_data_bytes bigint not null default 0;
do $$
begin
  if not exists (
    select 1 from pg_trigger
     where tgname in (
       'records_sync_usage_after_insert',
       'records_sync_usage_after_update',
       'records_sync_usage_after_delete'
     ) and not tgisinternal
  ) then
    update users u
       set sync_record_count = usage.record_count,
           sync_data_bytes = usage.data_bytes
      from (
        select u0.id,
               count(r.*)::integer as record_count,
               coalesce(sum(octet_length(r.data::text)), 0)::bigint as data_bytes
          from users u0
          left join records r on r.user_id = u0.id
         group by u0.id
      ) usage
     where u.id = usage.id;
  end if;
end
$$;
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'users_sync_record_count_bounds') then
    alter table users add constraint users_sync_record_count_bounds check
      (sync_record_count between 0 and 50000);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'users_sync_data_bytes_bounds') then
    alter table users add constraint users_sync_data_bytes_bounds check
      (sync_data_bytes between 0 and 134217728);
  end if;
end
$$;

create or replace function routino_records_usage_after_insert()
returns trigger language plpgsql as $$
begin
  update users u
     set sync_record_count = u.sync_record_count + delta.record_count,
         sync_data_bytes = u.sync_data_bytes + delta.data_bytes
    from (
      select user_id,
             count(*)::integer as record_count,
             coalesce(sum(octet_length(data::text)), 0)::bigint as data_bytes
        from new_rows
       group by user_id
    ) delta
   where u.id = delta.user_id;
  return null;
end
$$;

create or replace function routino_records_usage_after_update()
returns trigger language plpgsql as $$
begin
  update users u
     set sync_record_count = u.sync_record_count + delta.record_count,
         sync_data_bytes = u.sync_data_bytes + delta.data_bytes
    from (
      select user_id,
             sum(record_delta)::integer as record_count,
             sum(byte_delta)::bigint as data_bytes
        from (
          select user_id, -1 as record_delta,
                 -coalesce(octet_length(data::text), 0)::bigint as byte_delta
            from old_rows
          union all
          select user_id, 1 as record_delta,
                 coalesce(octet_length(data::text), 0)::bigint as byte_delta
            from new_rows
        ) changes
       group by user_id
    ) delta
   where u.id = delta.user_id
     and (delta.record_count <> 0 or delta.data_bytes <> 0);
  return null;
end
$$;

create or replace function routino_records_usage_after_delete()
returns trigger language plpgsql as $$
begin
  update users u
     set sync_record_count = u.sync_record_count - delta.record_count,
         sync_data_bytes = u.sync_data_bytes - delta.data_bytes
    from (
      select user_id,
             count(*)::integer as record_count,
             coalesce(sum(octet_length(data::text)), 0)::bigint as data_bytes
        from old_rows
       group by user_id
    ) delta
   where u.id = delta.user_id;
  return null;
end
$$;

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'records_sync_usage_after_insert') then
    create trigger records_sync_usage_after_insert
      after insert on records
      referencing new table as new_rows
      for each statement execute function routino_records_usage_after_insert();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'records_sync_usage_after_update') then
    create trigger records_sync_usage_after_update
      after update on records
      referencing old table as old_rows new table as new_rows
      for each statement execute function routino_records_usage_after_update();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'records_sync_usage_after_delete') then
    create trigger records_sync_usage_after_delete
      after delete on records
      referencing old table as old_rows
      for each statement execute function routino_records_usage_after_delete();
  end if;
end
$$;

create table if not exists otp_codes (
  id uuid primary key default gen_random_uuid(),
  phone text not null,
  code_hash text not null,
  expires_at timestamptz not null,
  attempts integer not null default 0,
  consumed_at timestamptz,
  ip text,
  created_at timestamptz not null default now()
);
create index if not exists otp_phone_recent on otp_codes (phone, created_at);
create index if not exists otp_ip_recent on otp_codes (ip, created_at);
-- The global daily circuit breaker counts the whole table by created_at with no
-- phone or ip to narrow it, on every single code request. It is also what the
-- 24h purge scans.
create index if not exists otp_recent on otp_codes (created_at);

create table if not exists auth_rate_limit_buckets (
  scope text not null,
  key_hash text not null,
  window_start timestamptz not null,
  count integer not null default 1,
  expires_at timestamptz not null,
  primary key (scope, key_hash, window_start),
  constraint auth_rate_limit_buckets_count_positive check (count >= 1)
);
create index if not exists auth_rate_limit_buckets_expiry
  on auth_rate_limit_buckets (expires_at);

create table if not exists plans (
  id text primary key,
  name_fa text not null,
  name_en text not null,
  months integer not null,
  price_toman integer not null,
  active boolean not null default true
);

create table if not exists discounts (
  code text primary key,
  percent integer not null,
  phone text,
  active boolean not null default true,
  max_uses integer,
  used_count integer not null default 0,
  expires_at timestamptz
);

create table if not exists redemptions (
  code text not null references discounts(code),
  user_id uuid not null references users(id) on delete cascade,
  payment_id uuid,
  created_at timestamptz not null default now(),
  primary key (code, user_id)
);

create table if not exists payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id),
  plan_id text not null,
  months integer not null,
  amount_toman integer not null,
  amount_rial bigint not null,
  discount_code text,
  discount_percent integer,
  offer_percent integer,
  status text not null default 'pending',
  platform text,
  attempt_id uuid not null default gen_random_uuid(),
  authority text unique,
  ref_number text,
  card_number text,
  psp_result integer,
  request_started_at timestamptz,
  verify_started_at timestamptz,
  next_verify_at timestamptz,
  verify_attempts integer not null default 0
    constraint payments_verify_attempts_nonnegative check (verify_attempts >= 0),
  paid_at timestamptz,
  verified_at timestamptz,
  applied_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table payments add column if not exists attempt_id uuid;
alter table payments add column if not exists request_started_at timestamptz;
alter table payments add column if not exists verify_started_at timestamptz;
alter table payments add column if not exists next_verify_at timestamptz;
alter table payments add column if not exists verify_attempts integer not null default 0;
update payments set attempt_id = gen_random_uuid() where attempt_id is null;
alter table payments alter column attempt_id set default gen_random_uuid();
alter table payments alter column attempt_id set not null;
do $$
declare
  has_legacy boolean := false;
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'payments' and column_name = 'provider'
  ) then
    execute $q$
      select exists (
        select 1 from payments
        where provider is not null and provider <> 'zarinpal'
          and applied_at is null and status not in ('failed', 'canceled')
      )
    $q$ into has_legacy;
  end if;
  if not has_legacy and exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'payments' and column_name = 'track_id'
  ) then
    execute $q$
      select exists (
        select 1 from payments
        where track_id is not null and applied_at is null
          and status not in ('failed', 'canceled')
      )
    $q$
      into has_legacy;
  end if;
  if has_legacy then
    raise exception 'unsettled legacy-provider payments require review before ZarinPal-only cleanup';
  end if;
end
$$;
drop index if exists payments_provider_ref_unique;
alter table payments drop column if exists provider;
alter table payments drop column if exists provider_ref;
alter table payments drop column if exists track_id;
alter table payments drop column if exists psp_status;
create index if not exists payments_user on payments (user_id);
create index if not exists payments_status on payments (status, created_at);
create unique index if not exists payments_user_attempt_unique
  on payments (user_id, attempt_id);
-- A limited discount code counts the checkouts currently in flight against it
-- (slotsTaken in services/pricing.ts), on the checkout path. Partial, because
-- most payments carry no code at all.
create index if not exists payments_discount on payments (discount_code) where discount_code is not null;

create table if not exists grants (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id) on delete cascade,
  months integer not null default 0,
  days integer not null default 0,
  source text not null,
  payment_id uuid,
  note text,
  expires_before timestamptz,
  expires_after timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists grants_user on grants (user_id);
-- Refuse to install the invariant over ambiguous history. Production operators
-- must inspect duplicate payment grants; startup/migration never deletes money
-- audit rows or guesses which entitlement extension was intended.
do $$
begin
  if exists (
    select 1 from grants
     where payment_id is not null
     group by payment_id
    having count(*) > 1
  ) then
    raise exception 'duplicate grants.payment_id rows must be resolved before enabling uniqueness';
  end if;
end
$$;
create unique index if not exists grants_payment_id_unique
  on grants (payment_id) where payment_id is not null;
-- settleOpenPayments asks "which paid payments have no grant behind them" on the
-- boot path, which is a NOT EXISTS against this column. Partial: admin gifts and
-- trials carry no payment_id and would only bloat it.
create index if not exists grants_payment on grants (payment_id) where payment_id is not null;

create table if not exists entitlements (
  user_id uuid primary key references users(id) on delete cascade,
  plan_id text not null,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create table if not exists feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) on delete set null,
  rating integer not null,
  section text,
  comment text,
  at timestamptz not null,
  created_at timestamptz not null default now()
);

-- Idempotent upgrades for databases created before a column existed. "create
-- table if not exists" silently skips existing tables, so new columns must be
-- added explicitly here.
alter table payments add column if not exists platform text;
alter table payments add column if not exists authority text;
-- ZarinPal authority is unique per transaction (multiple NULLs are allowed).
create unique index if not exists payments_authority on payments (authority);

-- Password + username sign-in (added after the users table already existed in
-- production). Both nullable: OTP-only accounts keep working untouched.
alter table users add column if not exists username text;
alter table users add column if not exists password_hash text;
-- username unique, but many NULLs allowed (unset accounts). Stored lowercased.
create unique index if not exists users_username on users (username);

-- records_habit indexed (data->>'habitId') for a query that was never written:
-- the habit-delete cascade matches the month id prefix (habitId|YYYY-MM), see
-- childMonthIds in services/sync.ts. An unused index is not free; dropped rather
-- than left "just in case". Re-add it WITH the query that uses it if that changes.
drop index if exists records_habit;

insert into plans (id, name_fa, name_en, months, price_toman) values
  ('m1',  'یک‌ماهه', '1 Month',  1,  59000),
  ('m3',  'سه‌ماهه', '3 Months', 3,  149000),
  ('m12', 'یک‌ساله', '1 Year',   12, 449000)
on conflict (id) do nothing;

-- Hourly purge of expired OTP rows (the Node backend did this with setInterval;
-- edge functions have no resident process, so the database does it itself).
-- OTP rows double as the rate-limit ledger, so they must live 24h first.
create extension if not exists pg_cron;
select cron.schedule('routino-otp-purge', '0 * * * *',
  $$delete from otp_codes where created_at < now() - interval '24 hours'$$);
-- Aggregate auth counters are bounded by key/window and expire automatically.
select cron.schedule('routino-auth-rate-limit-purge', '30 * * * *',
  $$delete from auth_rate_limit_buckets where expires_at < now()$$);

-- Tombstones, weekly. A deleted habit or log leaves a row behind on purpose: a
-- delete has to be able to TRAVEL to the user's other devices, and an absence
-- cannot. But it only has to travel once, and `records` is the table that
-- decides when the 500 MB fills up — so a user who tidies up their habits every
-- month should not keep paying for every one of them forever.
--
-- The two halves must happen together, which is why this is one statement.
-- Raising `users.gc_seq` to the highest seq removed is what makes deleting a
-- tombstone safe: any device whose cursor still sits below that line is told to
-- wipe and resync from zero (`reset: true` in services/sync.ts) instead of
-- being allowed to miss the delete and silently RESURRECT the record. Delete
-- without the bump and a phone left in a drawer for four months comes back with
-- every habit its owner ever threw away.
--
-- 90 days is the promise: a device offline longer than that pays for a full
-- resync, which is correct but not free, so do not shorten this casually.
select cron.schedule('routino-tombstone-purge', '45 3 * * 0', $$
  with doomed as (
    delete from records
     where deleted = true
       -- 86400000::bigint, not a bare 90 * 86400000: that product is 7.7e9, which
       -- overflows int4 and fails the whole job with "integer out of range" —
       -- weekly, quietly, in a cron log nobody reads.
       and updated_at < (extract(epoch from now()) * 1000)::bigint - 90 * 86400000::bigint
    returning user_id, seq
  ), highest as (
    select user_id, max(seq) as top from doomed group by user_id
  )
  update users u set gc_seq = greatest(u.gc_seq, h.top)
    from highest h where u.id = h.user_id
$$);

-- Lock every table out of Supabase's public PostgREST API (see comment in
-- scripts/gen-setup-sql.mjs). No policies are added on purpose: nothing but
-- the edge function's direct Postgres connection should ever touch these rows.
alter table users enable row level security;
alter table records enable row level security;
alter table otp_codes enable row level security;
alter table auth_rate_limit_buckets enable row level security;
alter table plans enable row level security;
alter table discounts enable row level security;
alter table redemptions enable row level security;
alter table payments enable row level security;
alter table grants enable row level security;
alter table entitlements enable row level security;
alter table feedback enable row level security;
