-- Routino database setup for Supabase.
-- Generated by scripts/gen-setup-sql.mjs from backend/src/db/ddl.ts (the same
-- DDL the test suites run) plus Supabase-hosting-specific sections below.
-- Idempotent (if not exists / on conflict) — safe to run more than once.
-- Apply: paste into the Supabase SQL Editor, or DATABASE_URL=... node scripts/apply-db-setup.mjs

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  phone text not null unique,
  username text,
  password_hash text,
  seq bigint not null default 0,
  gc_seq bigint not null default 0,
  blocked boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists records (
  user_id uuid not null references users(id) on delete cascade,
  kind text not null,
  id text not null,
  data jsonb,
  updated_at bigint not null,
  deleted boolean not null default false,
  seq bigint not null,
  primary key (user_id, kind, id),
  constraint records_kind_valid check (kind in
    ('categories','habits','logs','tasks','timerSessions','journal','settings'))
);
create index if not exists records_pull on records (user_id, seq);
create index if not exists records_habit on records (user_id, (data->>'habitId')) where kind = 'logs';

create table if not exists devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id) on delete cascade,
  refresh_hash text not null,
  name text,
  last_seen_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists devices_user on devices (user_id);
-- Every token refresh looks a device up by refresh_hash — roughly once per
-- active user per access-token lifetime (15 min), forever. Without this it is a
-- full scan of a table that only ever grows: one row per sign-in per device,
-- revoked rows included. Fine at a hundred users, not at ten thousand.
create index if not exists devices_refresh on devices (refresh_hash);

create table if not exists otp_codes (
  id uuid primary key default gen_random_uuid(),
  phone text not null,
  code_hash text not null,
  expires_at timestamptz not null,
  attempts integer not null default 0,
  consumed_at timestamptz,
  ip text,
  created_at timestamptz not null default now()
);
create index if not exists otp_phone_recent on otp_codes (phone, created_at);
create index if not exists otp_ip_recent on otp_codes (ip, created_at);
-- The global daily circuit breaker counts the whole table by created_at with no
-- phone or ip to narrow it, on every single code request. It is also what the
-- 24h purge scans.
create index if not exists otp_recent on otp_codes (created_at);

create table if not exists login_attempts (
  id uuid primary key default gen_random_uuid(),
  ip text,
  identifier text not null,
  created_at timestamptz not null default now()
);
create index if not exists login_attempts_identifier on login_attempts (identifier, created_at);
create index if not exists login_attempts_ip on login_attempts (ip, created_at);

create table if not exists plans (
  id text primary key,
  name_fa text not null,
  name_en text not null,
  months integer not null,
  price_toman integer not null,
  active boolean not null default true
);

create table if not exists discounts (
  code text primary key,
  percent integer not null,
  phone text,
  active boolean not null default true,
  max_uses integer,
  used_count integer not null default 0,
  expires_at timestamptz
);

create table if not exists redemptions (
  code text not null references discounts(code),
  user_id uuid not null references users(id) on delete cascade,
  payment_id uuid,
  created_at timestamptz not null default now(),
  primary key (code, user_id)
);

create table if not exists payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id),
  plan_id text not null,
  months integer not null,
  amount_toman integer not null,
  amount_rial bigint not null,
  discount_code text,
  discount_percent integer,
  offer_percent integer,
  status text not null default 'pending',
  platform text,
  provider text,
  track_id bigint unique,
  authority text unique,
  ref_number text,
  card_number text,
  psp_result integer,
  psp_status integer,
  paid_at timestamptz,
  verified_at timestamptz,
  applied_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists payments_user on payments (user_id);
create index if not exists payments_status on payments (status, created_at);
-- A limited discount code counts the checkouts currently in flight against it
-- (slotsTaken in services/pricing.ts), on the checkout path. Partial, because
-- most payments carry no code at all.
create index if not exists payments_discount on payments (discount_code) where discount_code is not null;

create table if not exists grants (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id) on delete cascade,
  months integer not null default 0,
  days integer not null default 0,
  source text not null,
  payment_id uuid,
  note text,
  expires_before timestamptz,
  expires_after timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists grants_user on grants (user_id);

create table if not exists entitlements (
  user_id uuid primary key references users(id) on delete cascade,
  plan_id text not null,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create table if not exists feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) on delete set null,
  rating integer not null,
  section text,
  comment text,
  at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists admins (
  user_id uuid primary key references users(id) on delete cascade,
  role text not null default 'admin'
);

-- Idempotent upgrades for databases created before a column existed. "create
-- table if not exists" silently skips existing tables, so new columns must be
-- added explicitly here.
alter table payments add column if not exists platform text;
alter table payments add column if not exists provider text;
alter table payments add column if not exists authority text;
-- authority is unique per transaction (multiple NULLs allowed for numeric gateways).
create unique index if not exists payments_authority on payments (authority);

-- Password + username sign-in (added after the users table already existed in
-- production). Both nullable: OTP-only accounts keep working untouched.
alter table users add column if not exists username text;
alter table users add column if not exists password_hash text;
-- username unique, but many NULLs allowed (unset accounts). Stored lowercased.
create unique index if not exists users_username on users (username);

insert into plans (id, name_fa, name_en, months, price_toman) values
  ('m1',  'یک‌ماهه', '1 Month',  1,  59000),
  ('m3',  'سه‌ماهه', '3 Months', 3,  149000),
  ('m12', 'یک‌ساله', '1 Year',   12, 449000)
on conflict (id) do nothing;

-- Hourly purge of expired OTP rows (the Node backend did this with setInterval;
-- edge functions have no resident process, so the database does it itself).
-- OTP rows double as the rate-limit ledger, so they must live 24h first.
create extension if not exists pg_cron;
select cron.schedule('routino-otp-purge', '0 * * * *',
  $$delete from otp_codes where created_at < now() - interval '24 hours'$$);
-- Same story for the failed-login ledger backing the password rate limits.
select cron.schedule('routino-login-attempts-purge', '30 * * * *',
  $$delete from login_attempts where created_at < now() - interval '24 hours'$$);

-- Revoked sessions, weekly. `devices` is the largest per-user table on this
-- schema (~550 bytes of the ~1.7 KB a user costs forever — see
-- supabase/tests/quota.test.ts), and a revoked row is pure dead weight:
-- rotateRefresh() only ever matches `revoked_at is null`, so the token behind
-- it is already rejected and nothing can bring it back. 30 days of grace is
-- kept purely so the row is still there to look at while investigating a
-- "someone got into my account" report.
--
-- Deliberately NOT extended to old un-revoked rows. Their refresh tokens do
-- expire (REFRESH_TTL_DAYS, measured from created_at), so they are technically
-- just as dead — but that would tie a cron job to an env var, and raising
-- REFRESH_TTL_DAYS later would then start signing people out early, silently.
-- Not worth it: at ~1.7 KB/user the 500 MB free tier holds ~300k users.
select cron.schedule('routino-devices-purge', '15 3 * * 0',
  $$delete from devices where revoked_at is not null and revoked_at < now() - interval '30 days'$$);

-- Lock every table out of Supabase's public PostgREST API (see comment in
-- scripts/gen-setup-sql.mjs). No policies are added on purpose: nothing but
-- the edge function's direct Postgres connection should ever touch these rows.
alter table users enable row level security;
alter table records enable row level security;
alter table devices enable row level security;
alter table otp_codes enable row level security;
alter table login_attempts enable row level security;
alter table plans enable row level security;
alter table discounts enable row level security;
alter table redemptions enable row level security;
alter table payments enable row level security;
alter table grants enable row level security;
alter table entitlements enable row level security;
alter table feedback enable row level security;
alter table admins enable row level security;
