-- Routino database setup for Supabase.
-- Generated by scripts/gen-setup-sql.mjs from backend/src/db/ddl.ts (the same
-- DDL the test suites run) plus Supabase-hosting-specific sections below.
-- Idempotent (if not exists / on conflict) — safe to run more than once.
-- Apply: paste into the Supabase SQL Editor, or DATABASE_URL=... node scripts/apply-db-setup.mjs

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  phone text not null unique,
  username text,
  password_hash text,
  seq bigint not null default 0,
  gc_seq bigint not null default 0,
  sync_record_count integer not null default 0,
  sync_data_bytes bigint not null default 0,
  sync_growth_period_started_at timestamptz not null default now(),
  sync_growth_bytes bigint not null default 0,
  constraint users_sync_record_count_bounds check
    (sync_record_count between 0 and 50000),
  constraint users_sync_data_bytes_nonnegative check (sync_data_bytes >= 0),
  constraint users_sync_growth_bytes_bounds check
    (sync_growth_bytes between 0 and 10485760),
  created_at timestamptz not null default now()
);
-- Pre-launch cleanup: these fields and tables are no longer part of the product.
drop table if exists device_security_events;
drop table if exists devices;
alter table users drop column if exists blocked;
alter table users drop column if exists max_active_devices;
alter table users drop column if exists security_locked_at;
alter table users drop column if exists security_lock_reason;
alter table users drop column if exists device_switch_reset_at;

create table if not exists records (
  user_id uuid not null references users(id) on delete cascade,
  kind text not null,
  id text not null,
  data jsonb,
  updated_at bigint not null,
  deleted boolean not null default false,
  seq bigint not null,
  primary key (user_id, kind, id),
  constraint records_kind_valid check (kind in
    ('categories','habits','habitMonths','tasks','timerSessions','journal','taskMonths'))
);
delete from records where kind = 'settings';
alter table records drop constraint if exists records_kind_valid;
alter table records add constraint records_kind_valid check (kind in
  ('categories','habits','habitMonths','tasks','timerSessions','journal','taskMonths'));
create index if not exists records_pull on records (user_id, seq);

-- Exact per-account storage accounting. Existing databases are backfilled only
-- while the trigger set is absent; normal boots see the triggers and skip the
-- aggregate scan entirely. Statement-level transition tables update each user
-- once per INSERT/UPDATE/DELETE statement, not once per record in a batch.
alter table users add column if not exists sync_record_count integer not null default 0;
alter table users add column if not exists sync_data_bytes bigint not null default 0;
alter table users add column if not exists
  sync_growth_period_started_at timestamptz not null default now();
alter table users add column if not exists sync_growth_bytes bigint not null default 0;
alter table users drop constraint if exists users_sync_data_bytes_bounds;
do $$
begin
  if not exists (
    select 1 from pg_trigger
     where tgname in (
       'records_sync_usage_after_insert',
       'records_sync_usage_after_update',
       'records_sync_usage_after_delete'
     ) and not tgisinternal
  ) then
    update users u
       set sync_record_count = usage.record_count,
           sync_data_bytes = usage.data_bytes
      from (
        select u0.id,
               count(r.*)::integer as record_count,
               coalesce(sum(octet_length(r.data::text)), 0)::bigint as data_bytes
          from users u0
          left join records r on r.user_id = u0.id
         group by u0.id
      ) usage
     where u.id = usage.id;
  end if;
end
$$;
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'users_sync_record_count_bounds') then
    alter table users add constraint users_sync_record_count_bounds check
      (sync_record_count between 0 and 50000);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'users_sync_data_bytes_nonnegative') then
    alter table users add constraint users_sync_data_bytes_nonnegative check
      (sync_data_bytes >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'users_sync_growth_bytes_bounds') then
    alter table users add constraint users_sync_growth_bytes_bounds check
      (sync_growth_bytes between 0 and 10485760);
  end if;
end
$$;

create or replace function routino_records_usage_after_insert()
returns trigger language plpgsql as $$
begin
  update users u
     set sync_record_count = u.sync_record_count + delta.record_count,
         sync_data_bytes = u.sync_data_bytes + delta.data_bytes
    from (
      select user_id,
             count(*)::integer as record_count,
             coalesce(sum(octet_length(data::text)), 0)::bigint as data_bytes
        from new_rows
       group by user_id
    ) delta
   where u.id = delta.user_id;
  return null;
end
$$;

create or replace function routino_records_usage_after_update()
returns trigger language plpgsql as $$
begin
  update users u
     set sync_record_count = u.sync_record_count + delta.record_count,
         sync_data_bytes = u.sync_data_bytes + delta.data_bytes
    from (
      select user_id,
             sum(record_delta)::integer as record_count,
             sum(byte_delta)::bigint as data_bytes
        from (
          select user_id, -1 as record_delta,
                 -coalesce(octet_length(data::text), 0)::bigint as byte_delta
            from old_rows
          union all
          select user_id, 1 as record_delta,
                 coalesce(octet_length(data::text), 0)::bigint as byte_delta
            from new_rows
        ) changes
       group by user_id
    ) delta
   where u.id = delta.user_id
     and (delta.record_count <> 0 or delta.data_bytes <> 0);
  return null;
end
$$;

create or replace function routino_records_usage_after_delete()
returns trigger language plpgsql as $$
begin
  update users u
     set sync_record_count = u.sync_record_count - delta.record_count,
         sync_data_bytes = u.sync_data_bytes - delta.data_bytes
    from (
      select user_id,
             count(*)::integer as record_count,
             coalesce(sum(octet_length(data::text)), 0)::bigint as data_bytes
        from old_rows
       group by user_id
    ) delta
   where u.id = delta.user_id;
  return null;
end
$$;

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'records_sync_usage_after_insert') then
    create trigger records_sync_usage_after_insert
      after insert on records
      referencing new table as new_rows
      for each statement execute function routino_records_usage_after_insert();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'records_sync_usage_after_update') then
    create trigger records_sync_usage_after_update
      after update on records
      referencing old table as old_rows new table as new_rows
      for each statement execute function routino_records_usage_after_update();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'records_sync_usage_after_delete') then
    create trigger records_sync_usage_after_delete
      after delete on records
      referencing old table as old_rows
      for each statement execute function routino_records_usage_after_delete();
  end if;
end
$$;

-- One client round trip, two server commands: the first command acquires the
-- per-owner lock; the volatile function's RETURN QUERY then reads a fresh
-- READ COMMITTED snapshot. This avoids the stale statement-snapshot race that
-- a single lock-and-read CTE would have after waiting for another device.
create or replace function routino_push_records(
  p_user_id uuid,
  p_now timestamptz,
  p_incoming jsonb
)
returns table (
  cursor bigint,
  applied bigint,
  skipped bigint,
  quota_rejected jsonb
)
language plpgsql
volatile
security invoker
set search_path = public, pg_temp
as $function$
begin
  perform 1 from users u where u.id = p_user_id for update;
  if not found then
    raise exception 'unknown sync user';
  end if;

  return query
  with recursive incoming (
    kind, id, data, updated_at, original_updated_at, deleted, ord
  ) as (
    select item.value->>'kind',
           item.value->>'id',
           item.value->'data',
           (item.value->>'updatedAt')::bigint,
           (item.value->>'originalUpdatedAt')::bigint,
           (item.value->>'deleted')::boolean,
           item.ord::bigint
      from jsonb_array_elements(p_incoming) with ordinality item(value, ord)
  ),
  cascaded (
    kind, id, data, updated_at, original_updated_at, deleted, ord
  ) as (
    select 'habitMonths'::text, child.id, null::jsonb,
           parent.updated_at, parent.original_updated_at, true,
           jsonb_array_length(p_incoming)::bigint
             + row_number() over (order by child.id)
      from incoming parent
      join records child
        on child.user_id = p_user_id
       and child.kind = 'habitMonths'
       and child.deleted = false
       and child.id like parent.id || '|%'
     where parent.kind = 'habits' and parent.deleted = true
  ),
  deduped as (
    select distinct on (combined.kind, combined.id)
           combined.kind, combined.id, combined.data, combined.updated_at,
           combined.original_updated_at, combined.deleted, combined.ord
      from (
        select * from incoming
        union all
        select * from cascaded
      ) combined
     order by combined.kind, combined.id, combined.updated_at desc,
              combined.deleted desc, combined.ord
  ),
  current_state as (
    select u.sync_growth_period_started_at, u.sync_growth_bytes, u.sync_record_count
      from users u where u.id = p_user_id
  ),
  effective_period as (
    select case
             when cs.sync_growth_period_started_at + interval '365 days' <= p_now
               then p_now
             else cs.sync_growth_period_started_at
           end as period_start,
           case
             when cs.sync_growth_period_started_at + interval '365 days' <= p_now
               then 0::bigint
             else cs.sync_growth_bytes
           end as base_used,
           greatest(50000::bigint - cs.sync_record_count, 0::bigint) as row_slots
      from current_state cs
  ),
  prepared as (
    select d.kind, d.id,
           final.final_data as data,
           final.final_updated_at as updated_at,
           d.original_updated_at,
           final.final_deleted as deleted,
           d.ord,
           (existing.user_id is null) as is_insert,
           decision.will_apply,
           greatest(
             coalesce(octet_length(final.final_data::text), 0) -
             coalesce(octet_length(existing.data::text), 0),
             0
           )::bigint as positive_growth
      from deduped d
      left join records existing
        on existing.user_id = p_user_id
       and existing.kind = d.kind
       and existing.id = d.id
      cross join lateral (
        select case
                 when d.kind = 'habitMonths'
                  and d.deleted = false
                  and existing.user_id is not null
                  and existing.deleted = false
                 then jsonb_build_object(
                   'habitId', d.data->'habitId',
                   'monthKey', d.data->'monthKey',
                   'cells', coalesce(existing.data->'cells', '{}'::jsonb) || coalesce((
                     select jsonb_object_agg(incoming_cell.key, incoming_cell.value)
                       from jsonb_each(d.data->'cells') incoming_cell
                      where coalesce(
                        (existing.data->'cells'->incoming_cell.key->>'updatedAt')::bigint,
                        -1
                      ) < (incoming_cell.value->>'updatedAt')::bigint
                   ), '{}'::jsonb)
                 )
                 else d.data
               end as final_data,
               case
                 when d.kind = 'habitMonths'
                  and d.deleted = false
                  and existing.user_id is not null
                  and existing.deleted = false
                 then greatest(existing.updated_at, d.updated_at)
                 else d.updated_at
               end as final_updated_at,
               case
                 when d.kind = 'habitMonths'
                  and d.deleted = false
                  and existing.user_id is not null
                  and existing.deleted = false
                 then false
                 else d.deleted
               end as final_deleted
      ) final
      cross join lateral (
        select case
                 when existing.user_id is null then true
                 when d.kind = 'habitMonths' then case
                   when d.deleted = true or existing.deleted = true
                     then existing.updated_at < d.updated_at
                   else exists (
                     select 1
                       from jsonb_each(d.data->'cells') incoming_cell
                      where coalesce(
                        (existing.data->'cells'->incoming_cell.key->>'updatedAt')::bigint,
                        -1
                      ) < (incoming_cell.value->>'updatedAt')::bigint
                   )
                 end
                 else existing.updated_at < d.updated_at
               end as will_apply
      ) decision
  ),
  ranked as (
    select p.*,
           10485760::bigint - ep.base_used as allowance_remaining,
           ep.row_slots
      from prepared p cross join effective_period ep
  ),
  positive_candidates as (
    select r.*,
           row_number() over (order by r.ord, r.kind, r.id)::bigint as budget_position
      from ranked r
     where r.will_apply and r.positive_growth > 0
  ),
  budget_walk as (
    select pc.*,
           (pc.positive_growth <= pc.allowance_remaining) as budget_accepted,
           case when pc.positive_growth <= pc.allowance_remaining
             then pc.positive_growth else 0::bigint end as accepted_growth
      from positive_candidates pc where pc.budget_position = 1
    union all
    select pc.*,
           (walk.accepted_growth + pc.positive_growth <= pc.allowance_remaining),
           case
             when walk.accepted_growth + pc.positive_growth <= pc.allowance_remaining
               then walk.accepted_growth + pc.positive_growth
             else walk.accepted_growth
           end
      from budget_walk walk
      join positive_candidates pc
        on pc.budget_position = walk.budget_position + 1
  ),
  budget_accepted_pre as (
    select r.kind, r.id, r.data, r.updated_at, r.original_updated_at,
           r.deleted, r.ord, r.positive_growth, r.is_insert, r.row_slots
      from ranked r
     where r.will_apply and r.positive_growth = 0
    union all
    select walk.kind, walk.id, walk.data, walk.updated_at,
           walk.original_updated_at, walk.deleted, walk.ord, walk.positive_growth,
           walk.is_insert, walk.row_slots
      from budget_walk walk where walk.budget_accepted
  ),
  capacity_candidates as (
    select accepted_pre.*,
           row_number() over (order by accepted_pre.ord, accepted_pre.kind, accepted_pre.id)::bigint as capacity_position
      from budget_accepted_pre accepted_pre
  ),
  capacity_walk as (
    select cc.*,
           (not cc.is_insert or cc.row_slots >= 1) as capacity_accepted,
           case when cc.is_insert and cc.row_slots >= 1 then 1::bigint else 0::bigint end as accepted_inserts
      from capacity_candidates cc where cc.capacity_position = 1
    union all
    select cc.*,
           (not cc.is_insert or walk.accepted_inserts + 1 <= cc.row_slots),
           case
             when cc.is_insert and walk.accepted_inserts + 1 <= cc.row_slots
               then walk.accepted_inserts + 1
             else walk.accepted_inserts
           end
      from capacity_walk walk
      join capacity_candidates cc on cc.capacity_position = walk.capacity_position + 1
  ),
  accepted as (
    select capacity.*,
           row_number() over (
             order by capacity.ord, capacity.kind, capacity.id
           )::bigint as position
      from capacity_walk capacity where capacity.capacity_accepted
  ),
  budget_rejected as (
    select walk.kind, walk.id, walk.original_updated_at, walk.ord
      from budget_walk walk where not walk.budget_accepted
  ),
  capacity_rejected as (
    select walk.kind, walk.id, walk.original_updated_at, walk.ord
      from capacity_walk walk where not walk.capacity_accepted
  ),
  sized as (
    select count(*)::bigint as total,
           coalesce(sum(accepted.positive_growth), 0)::bigint as positive_growth
      from accepted
  ),
  bump as (
    update users u
       set seq = u.seq + sized.total,
           sync_growth_period_started_at = ep.period_start,
           sync_growth_bytes = ep.base_used + sized.positive_growth
      from sized cross join effective_period ep
     where u.id = p_user_id
    returning u.seq,
              u.sync_growth_period_started_at + interval '365 days' as retry_at
  ),
  upserted as (
    insert into records (user_id, kind, id, data, updated_at, deleted, seq)
    select p_user_id, accepted.kind, accepted.id, accepted.data,
           accepted.updated_at, accepted.deleted,
           bump.seq - sized.total + accepted.position
      from accepted cross join sized cross join bump
    on conflict (user_id, kind, id) do update
      set data = case
            when excluded.kind = 'habitMonths'
             and excluded.deleted = false
             and records.deleted = false
            then jsonb_build_object(
              'habitId', excluded.data->'habitId',
              'monthKey', excluded.data->'monthKey',
              'cells', coalesce(records.data->'cells', '{}'::jsonb) || coalesce((
                select jsonb_object_agg(incoming_cell.key, incoming_cell.value)
                  from jsonb_each(excluded.data->'cells') incoming_cell
                 where coalesce(
                   (records.data->'cells'->incoming_cell.key->>'updatedAt')::bigint,
                   -1
                 ) < (incoming_cell.value->>'updatedAt')::bigint
              ), '{}'::jsonb)
            )
            else excluded.data
          end,
          updated_at = case
            when excluded.kind = 'habitMonths'
             and excluded.deleted = false
             and records.deleted = false
            then greatest(records.updated_at, excluded.updated_at)
            else excluded.updated_at
          end,
          deleted = case
            when excluded.kind = 'habitMonths'
             and excluded.deleted = false
             and records.deleted = false
            then false
            else excluded.deleted
          end,
          seq = excluded.seq
      where case
        when excluded.kind = 'habitMonths' then case
          when excluded.deleted = true or records.deleted = true
            then records.updated_at < excluded.updated_at
          else exists (
            select 1
              from jsonb_each(excluded.data->'cells') incoming_cell
             where coalesce(
               (records.data->'cells'->incoming_cell.key->>'updatedAt')::bigint,
               -1
             ) < (incoming_cell.value->>'updatedAt')::bigint
          )
        end
        else records.updated_at < excluded.updated_at
      end
    returning 1
  )
  select bump.seq,
         (select count(*)::bigint from upserted),
         (select count(*)::bigint from prepared where not prepared.will_apply),
         coalesce((
           select jsonb_agg(
             jsonb_build_object(
               'kind', rejected.kind,
               'id', rejected.id,
               'updatedAt', rejected.original_updated_at,
               'code', 'account_quota_exceeded',
               'retryAt', rejected.retry_at
             ) order by rejected.ord, rejected.kind, rejected.id
           ) from (
             select annual.kind, annual.id, annual.original_updated_at, annual.ord,
                    floor(extract(epoch from bump.retry_at) * 1000)::bigint as retry_at
               from budget_rejected annual cross join bump
             union all
             select row_cap.kind, row_cap.id, row_cap.original_updated_at, row_cap.ord,
                    floor(extract(epoch from (p_now + interval '1 day')) * 1000)::bigint
               from capacity_rejected row_cap
           ) rejected
         ), '[]'::jsonb)
    from bump;
end
$function$;

revoke execute on function routino_push_records(uuid, timestamptz, jsonb) from public;

-- JavaScript/Zod count string bounds in UTF-16 code units. PostgreSQL counts
-- Unicode scalar values, so each non-BMP character needs one extra unit here.
create or replace function routino_js_string_length(p_text text)
returns integer
language sql
immutable
strict
parallel safe
set search_path = public, pg_temp
as $function$
  select (
    char_length(p_text) + count(*) filter (
      where octet_length(substr(p_text, position, 1)) = 4
    )
  )::integer
    from generate_series(1, char_length(p_text)) position
$function$;

-- Fail-closed copy of the canonical TypeScript task validator. Only payloads
-- which can be reconstructed as ordinary v2 task envelopes may be archived.
create or replace function routino_task_archive_candidate_valid(
  p_id text,
  p_data jsonb
)
returns boolean
language plpgsql
immutable
strict
parallel safe
set search_path = public, pg_temp
as $function$
declare
  v_year integer;
  v_month integer;
  v_day integer;
  v_max_day integer;
begin
  -- Bound attacker/legacy work before any per-character UTF-16 scan. This is a
  -- separate statement because SQL does not guarantee boolean evaluation order.
  if jsonb_typeof(p_data) <> 'object' or octet_length(p_data::text) > 20480 then
    return false;
  end if;

  if p_id !~ '^[A-Za-z0-9_:.-]{1,128}$'
     or not (p_data ?& array['id','dateKey','title','type','target','value','done'])
     or p_data - array[
       'id','dateKey','title','type','target','value','done',
       'note','unitKind','reminderAt','color','icon'
     ] <> '{}'::jsonb
     or jsonb_typeof(p_data->'id') <> 'string'
     or p_data->>'id' <> p_id
     or jsonb_typeof(p_data->'dateKey') <> 'string'
     or p_data->>'dateKey' !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
     or jsonb_typeof(p_data->'title') <> 'string'
     or routino_js_string_length(p_data->>'title') not between 1 and 256
     or jsonb_typeof(p_data->'type') <> 'string'
     or p_data->>'type' not in ('binary', 'quantity')
     or jsonb_typeof(p_data->'target') <> 'number'
     or (p_data->>'target')::numeric not between 0 and 1000000000
     or jsonb_typeof(p_data->'value') <> 'number'
     or (p_data->>'value')::numeric not between 0 and 1000000000
     or jsonb_typeof(p_data->'done') <> 'boolean'
     or (
       p_data ? 'note' and (
         jsonb_typeof(p_data->'note') <> 'string'
         or routino_js_string_length(p_data->>'note') > 4000
       )
     )
     or (
       p_data ? 'unitKind' and (
         jsonb_typeof(p_data->'unitKind') <> 'string'
         or p_data->>'unitKind' not in ('count', 'time')
       )
     )
     or (
       p_data ? 'reminderAt'
       and jsonb_typeof(p_data->'reminderAt') <> 'null'
       and (
         jsonb_typeof(p_data->'reminderAt') <> 'string'
         or routino_js_string_length(p_data->>'reminderAt') > 64
       )
     )
     or (
       p_data ? 'color' and (
         jsonb_typeof(p_data->'color') <> 'string'
         or routino_js_string_length(p_data->>'color') > 32
       )
     )
     or (
       p_data ? 'icon' and (
         jsonb_typeof(p_data->'icon') <> 'string'
         or routino_js_string_length(p_data->>'icon') > 64
       )
     ) then
    return false;
  end if;

  v_year := substring(p_data->>'dateKey' from 1 for 4)::integer;
  v_month := substring(p_data->>'dateKey' from 6 for 2)::integer;
  v_day := substring(p_data->>'dateKey' from 9 for 2)::integer;
  if v_month not between 1 and 12 then return false; end if;
  v_max_day := case v_month
    when 2 then case
      when v_year % 4 = 0 and (v_year % 100 <> 0 or v_year % 400 = 0) then 29
      else 28
    end
    when 4 then 30 when 6 then 30 when 9 then 30 when 11 then 30
    else 31
  end;
  return v_day between 1 and v_max_day;
exception when others then
  return false;
end
$function$;

-- Re-encode a small deterministic set of cold completed tasks. Row locks are
-- skipped instead of waited on, and every source/delete is verified in the
-- same transaction as its immutable archive insert.
create or replace function routino_compact_task_months(
  p_now timestamptz,
  p_max_tasks integer
)
returns table (
  owner_id uuid,
  month_key text,
  archived_tasks integer,
  archive_rows integer
)
language plpgsql
volatile
security invoker
set search_path = public, pg_temp
as $function$
declare
  v_limit integer := greatest(1, least(coalesce(p_max_tasks, 1), 500));
  v_group record;
  v_task record;
  v_chunk integer;
  v_chunk_count integer;
  v_chunk_bytes bigint;
  v_archive_rows integer;
  v_archived_tasks integer;
  v_end_seq bigint;
  v_deleted integer;
begin
  create temp table if not exists routino_compaction_selected (
    user_id uuid not null,
    task_id text not null,
    task_data jsonb not null,
    updated_at bigint not null,
    month_key text not null,
    envelope_bytes integer not null,
    primary key (user_id, task_id)
  ) on commit drop;
  create temp table if not exists routino_compaction_items (
    user_id uuid not null,
    month_key text not null,
    chunk_no integer not null,
    task_id text not null,
    task_data jsonb not null,
    updated_at bigint not null,
    envelope_bytes integer not null,
    primary key (user_id, month_key, chunk_no, task_id)
  ) on commit drop;
  truncate pg_temp.routino_compaction_selected;
  truncate pg_temp.routino_compaction_items;

  -- Claim owners before source tasks. Foreground sync takes this same owner
  -- lock first, so a busy owner is skipped without retaining any task locks.
  with candidate_owners as materialized (
    select source.user_id
      from records source
     where source.kind = 'tasks'
       and source.deleted = false
       and source.data->>'done' = 'true'
       and routino_task_archive_candidate_valid(source.id, source.data)
       and source.updated_at between 0 and 9007199254740991
       and left(source.data->>'dateKey', 7) < to_char(
         (p_now - interval '7 days') at time zone 'UTC', 'YYYY-MM'
       )
       and source.updated_at <= floor(
         extract(epoch from (p_now - interval '7 days')) * 1000
       )::bigint
       and not exists (
         select 1 from records archive
         cross join lateral jsonb_array_elements(
           case when jsonb_typeof(archive.data->'items') = 'array'
             then archive.data->'items' else '[]'::jsonb end
         ) item
          where archive.user_id = source.user_id
            and archive.kind = 'taskMonths'
            and item->>0 = source.id
       )
     group by source.user_id
     order by source.user_id
     limit v_limit
  ),
  locked_owners as materialized (
    select u.id
      from users u
      join candidate_owners candidate on candidate.user_id = u.id
     order by u.id
     for update of u skip locked
  ),
  locked as (
    select source.user_id,
           source.id as task_id,
           source.data as task_data,
           source.updated_at,
           left(source.data->>'dateKey', 7) as month_key,
           octet_length(jsonb_build_object(
             'kind', 'tasks',
             'id', source.id,
             'data', source.data,
             'updatedAt', source.updated_at,
             'deleted', false
           )::text)::integer as envelope_bytes
      from records source
      join locked_owners owner on owner.id = source.user_id
     where source.kind = 'tasks'
       and source.deleted = false
       and source.data->>'done' = 'true'
       and routino_task_archive_candidate_valid(source.id, source.data)
       and source.updated_at between 0 and 9007199254740991
       and left(source.data->>'dateKey', 7) < to_char(
         (p_now - interval '7 days') at time zone 'UTC', 'YYYY-MM'
       )
       and source.updated_at <= floor(
         extract(epoch from (p_now - interval '7 days')) * 1000
       )::bigint
       and not exists (
         select 1
           from records archive
           cross join lateral jsonb_array_elements(
             case when jsonb_typeof(archive.data->'items') = 'array'
               then archive.data->'items' else '[]'::jsonb end
           ) item
          where archive.user_id = source.user_id
            and archive.kind = 'taskMonths'
            and item->>0 = source.id
       )
     order by source.user_id, left(source.data->>'dateKey', 7), source.id
     limit v_limit
     for update of source skip locked
  )
  insert into pg_temp.routino_compaction_selected (
    user_id, task_id, task_data, updated_at, month_key, envelope_bytes
  )
  select locked.user_id, locked.task_id, locked.task_data, locked.updated_at,
         locked.month_key, locked.envelope_bytes
    from locked;

  for v_group in
    select selected.user_id, selected.month_key
      from pg_temp.routino_compaction_selected selected
     group by selected.user_id, selected.month_key
     order by selected.user_id, selected.month_key
  loop
    v_chunk := 1;
    v_chunk_count := 0;
    v_chunk_bytes := 0;
    for v_task in
      select selected.*
        from pg_temp.routino_compaction_selected selected
       where selected.user_id = v_group.user_id
         and selected.month_key = v_group.month_key
       order by selected.task_id
    loop
      if v_chunk_count > 0 and (
        v_chunk_count >= 32 or v_chunk_bytes + v_task.envelope_bytes > 98304
      ) then
        v_chunk := v_chunk + 1;
        v_chunk_count := 0;
        v_chunk_bytes := 0;
      end if;
      insert into pg_temp.routino_compaction_items (
        user_id, month_key, chunk_no, task_id, task_data, updated_at, envelope_bytes
      ) values (
        v_task.user_id, v_task.month_key, v_chunk, v_task.task_id,
        v_task.task_data, v_task.updated_at, v_task.envelope_bytes
      );
      v_chunk_count := v_chunk_count + 1;
      v_chunk_bytes := v_chunk_bytes + v_task.envelope_bytes;
    end loop;

    select count(*)::integer into v_archive_rows
      from (
        select items.chunk_no
          from pg_temp.routino_compaction_items items
         where items.user_id = v_group.user_id
           and items.month_key = v_group.month_key
         group by items.chunk_no
      ) chunks;
    select count(*)::integer into v_archived_tasks
      from pg_temp.routino_compaction_selected selected
     where selected.user_id = v_group.user_id
       and selected.month_key = v_group.month_key;

    -- Reserve row-cap headroom for the archive inserts. This temporary counter
    -- reservation is invisible before commit and is restored after source
    -- deletion; the existing triggers still account for both physical writes.
    update users u
       set seq = u.seq + v_archive_rows,
           sync_record_count = u.sync_record_count - v_archive_rows
     where u.id = v_group.user_id
    returning u.seq into v_end_seq;

    insert into records (user_id, kind, id, data, updated_at, deleted, seq)
    select v_group.user_id,
           'taskMonths',
           v_group.month_key || '|' || md5(string_agg(items.task_id, E'\n' order by items.task_id)),
           jsonb_build_object(
             'v', 1,
             'monthKey', v_group.month_key,
             'count', count(*)::integer,
             'checksum', md5(string_agg(
               items.task_id || E'\n' || items.updated_at::text || E'\n' || items.task_data::text,
               E'\n' order by items.task_id
             )),
             'items', jsonb_agg(
               jsonb_build_array(items.task_id, items.updated_at, items.task_data)
               order by items.task_id
             )
           ),
           max(items.updated_at),
           false,
           v_end_seq - v_archive_rows + items.chunk_no
      from pg_temp.routino_compaction_items items
     where items.user_id = v_group.user_id
       and items.month_key = v_group.month_key
     group by items.chunk_no
     order by items.chunk_no;

    if exists (
      select 1
        from records archive
        join (
          select items.chunk_no,
                 v_group.month_key || '|' || md5(string_agg(items.task_id, E'\n' order by items.task_id)) as archive_id,
                 count(*)::integer as item_count,
                 md5(string_agg(
                   items.task_id || E'\n' || items.updated_at::text || E'\n' || items.task_data::text,
                   E'\n' order by items.task_id
                 )) as checksum
            from pg_temp.routino_compaction_items items
           where items.user_id = v_group.user_id
             and items.month_key = v_group.month_key
           group by items.chunk_no
        ) expected on expected.archive_id = archive.id
       where archive.user_id = v_group.user_id
         and archive.kind = 'taskMonths'
         and (
           archive.deleted
           or archive.data->'v' is distinct from '1'::jsonb
           or archive.data->>'monthKey' is distinct from v_group.month_key
           or (archive.data->>'count')::integer is distinct from expected.item_count
           or jsonb_array_length(archive.data->'items') is distinct from expected.item_count
           or archive.data->>'checksum' is distinct from expected.checksum
           or (archive.data->>'count')::integer is distinct from jsonb_array_length(archive.data->'items')
           or archive.data->>'checksum' is distinct from (
             select md5(string_agg(
               item->>0 || E'\n' || (item->>1)::bigint::text || E'\n' || (item->2)::text,
               E'\n' order by item->>0
             ))
               from jsonb_array_elements(archive.data->'items') item
           )
         )
    ) then
      raise exception 'task archive verification failed: metadata mismatch';
    end if;

    if exists (
      (
        select selected.task_id, selected.updated_at, selected.task_data
          from pg_temp.routino_compaction_selected selected
         where selected.user_id = v_group.user_id
           and selected.month_key = v_group.month_key
        except
        select item->>0, (item->>1)::bigint, item->2
          from records archive
          join (
            select v_group.month_key || '|' || md5(string_agg(items.task_id, E'\n' order by items.task_id)) as archive_id
              from pg_temp.routino_compaction_items items
             where items.user_id = v_group.user_id
               and items.month_key = v_group.month_key
             group by items.chunk_no
          ) expected on expected.archive_id = archive.id
          cross join lateral jsonb_array_elements(archive.data->'items') item
         where archive.user_id = v_group.user_id and archive.kind = 'taskMonths'
      )
      union all
      (
        select item->>0, (item->>1)::bigint, item->2
          from records archive
          join (
            select v_group.month_key || '|' || md5(string_agg(items.task_id, E'\n' order by items.task_id)) as archive_id
              from pg_temp.routino_compaction_items items
             where items.user_id = v_group.user_id
               and items.month_key = v_group.month_key
             group by items.chunk_no
          ) expected on expected.archive_id = archive.id
          cross join lateral jsonb_array_elements(archive.data->'items') item
         where archive.user_id = v_group.user_id and archive.kind = 'taskMonths'
        except
        select selected.task_id, selected.updated_at, selected.task_data
          from pg_temp.routino_compaction_selected selected
         where selected.user_id = v_group.user_id
           and selected.month_key = v_group.month_key
      )
    ) then
      raise exception 'task archive verification failed: source mismatch';
    end if;

    delete from records source
     using pg_temp.routino_compaction_selected selected
     where selected.user_id = v_group.user_id
       and selected.month_key = v_group.month_key
       and source.user_id = selected.user_id
       and source.kind = 'tasks'
       and source.id = selected.task_id
       and source.updated_at = selected.updated_at
       and source.data = selected.task_data
       and source.deleted = false;
    get diagnostics v_deleted = row_count;
    if v_deleted <> v_archived_tasks then
      raise exception 'task archive verification failed: delete mismatch';
    end if;

    update users u
       set sync_record_count = u.sync_record_count + v_archive_rows
     where u.id = v_group.user_id;

    owner_id := v_group.user_id;
    month_key := v_group.month_key;
    archived_tasks := v_archived_tasks;
    archive_rows := v_archive_rows;
    return next;
  end loop;
end
$function$;

-- The scheduled command sets transaction-local timeouts BEFORE it invokes this
-- thin wrapper. Keeping the call target named makes the cron contract auditable
-- without pretending a timeout set inside an already-running SELECT is enough.
create or replace function routino_run_task_month_compaction(
  p_now timestamptz,
  p_max_tasks integer
)
returns table (
  owner_id uuid,
  month_key text,
  archived_tasks integer,
  archive_rows integer
)
language sql
volatile
security invoker
set search_path = public, pg_temp
as $function$
  select * from routino_compact_task_months(p_now, p_max_tasks)
$function$;

revoke execute on function routino_js_string_length(text) from public;
revoke execute on function routino_task_archive_candidate_valid(text, jsonb) from public;
revoke execute on function routino_compact_task_months(timestamptz, integer) from public;
revoke execute on function routino_run_task_month_compaction(timestamptz, integer) from public;

create table if not exists otp_codes (
  id uuid primary key default gen_random_uuid(),
  phone text not null,
  code_hash text not null,
  expires_at timestamptz not null,
  attempts integer not null default 0,
  consumed_at timestamptz,
  ip text,
  created_at timestamptz not null default now()
);
create index if not exists otp_phone_recent on otp_codes (phone, created_at);
create index if not exists otp_ip_recent on otp_codes (ip, created_at);
-- The global daily circuit breaker counts the whole table by created_at with no
-- phone or ip to narrow it, on every single code request. It is also what the
-- 24h purge scans.
create index if not exists otp_recent on otp_codes (created_at);

create table if not exists auth_rate_limit_buckets (
  scope text not null,
  key_hash text not null,
  window_start timestamptz not null,
  count integer not null default 1,
  expires_at timestamptz not null,
  primary key (scope, key_hash, window_start),
  constraint auth_rate_limit_buckets_count_positive check (count >= 1)
);
create index if not exists auth_rate_limit_buckets_expiry
  on auth_rate_limit_buckets (expires_at);

create table if not exists plans (
  id text primary key,
  name_fa text not null,
  name_en text not null,
  months integer not null,
  price_toman integer not null,
  active boolean not null default true
);

create table if not exists discounts (
  code text primary key,
  percent integer not null,
  phone text,
  active boolean not null default true,
  max_uses integer,
  used_count integer not null default 0,
  expires_at timestamptz
);

create table if not exists redemptions (
  code text not null references discounts(code),
  user_id uuid not null references users(id) on delete cascade,
  payment_id uuid,
  created_at timestamptz not null default now(),
  primary key (code, user_id)
);

create table if not exists payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id),
  plan_id text not null,
  months integer not null,
  amount_toman integer not null,
  amount_rial bigint not null,
  discount_code text,
  discount_percent integer,
  offer_percent integer,
  status text not null default 'pending',
  platform text,
  attempt_id uuid not null default gen_random_uuid(),
  authority text unique,
  ref_number text,
  card_number text,
  psp_result integer,
  request_started_at timestamptz,
  verify_started_at timestamptz,
  next_verify_at timestamptz,
  verify_attempts integer not null default 0
    constraint payments_verify_attempts_nonnegative check (verify_attempts >= 0),
  paid_at timestamptz,
  verified_at timestamptz,
  applied_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table payments add column if not exists attempt_id uuid;
alter table payments add column if not exists request_started_at timestamptz;
alter table payments add column if not exists verify_started_at timestamptz;
alter table payments add column if not exists next_verify_at timestamptz;
alter table payments add column if not exists verify_attempts integer not null default 0;
update payments set attempt_id = gen_random_uuid() where attempt_id is null;
alter table payments alter column attempt_id set default gen_random_uuid();
alter table payments alter column attempt_id set not null;
do $$
declare
  has_legacy boolean := false;
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'payments' and column_name = 'provider'
  ) then
    execute $q$
      select exists (
        select 1 from payments
        where provider is not null and provider <> 'zarinpal'
          and applied_at is null and status not in ('failed', 'canceled')
      )
    $q$ into has_legacy;
  end if;
  if not has_legacy and exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'payments' and column_name = 'track_id'
  ) then
    execute $q$
      select exists (
        select 1 from payments
        where track_id is not null and applied_at is null
          and status not in ('failed', 'canceled')
      )
    $q$
      into has_legacy;
  end if;
  if has_legacy then
    raise exception 'unsettled legacy-provider payments require review before ZarinPal-only cleanup';
  end if;
end
$$;
drop index if exists payments_provider_ref_unique;
alter table payments drop column if exists provider;
alter table payments drop column if exists provider_ref;
alter table payments drop column if exists track_id;
alter table payments drop column if exists psp_status;
create index if not exists payments_user on payments (user_id);
create index if not exists payments_status on payments (status, created_at);
create unique index if not exists payments_user_attempt_unique
  on payments (user_id, attempt_id);
-- A limited discount code counts the checkouts currently in flight against it
-- (slotsTaken in services/pricing.ts), on the checkout path. Partial, because
-- most payments carry no code at all.
create index if not exists payments_discount on payments (discount_code) where discount_code is not null;

create table if not exists grants (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id) on delete cascade,
  months integer not null default 0,
  days integer not null default 0,
  source text not null,
  payment_id uuid,
  note text,
  expires_before timestamptz,
  expires_after timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists grants_user on grants (user_id);
-- Refuse to install the invariant over ambiguous history. Production operators
-- must inspect duplicate payment grants; startup/migration never deletes money
-- audit rows or guesses which entitlement extension was intended.
do $$
begin
  if exists (
    select 1 from grants
     where payment_id is not null
     group by payment_id
    having count(*) > 1
  ) then
    raise exception 'duplicate grants.payment_id rows must be resolved before enabling uniqueness';
  end if;
end
$$;
create unique index if not exists grants_payment_id_unique
  on grants (payment_id) where payment_id is not null;
-- settleOpenPayments asks "which paid payments have no grant behind them" on the
-- boot path, which is a NOT EXISTS against this column. Partial: admin gifts and
-- trials carry no payment_id and would only bloat it.
create index if not exists grants_payment on grants (payment_id) where payment_id is not null;

create table if not exists entitlements (
  user_id uuid primary key references users(id) on delete cascade,
  plan_id text not null,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create table if not exists feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) on delete set null,
  rating integer not null,
  section text,
  comment text,
  at timestamptz not null,
  created_at timestamptz not null default now()
);

-- Idempotent upgrades for databases created before a column existed. "create
-- table if not exists" silently skips existing tables, so new columns must be
-- added explicitly here.
alter table payments add column if not exists platform text;
alter table payments add column if not exists authority text;
-- ZarinPal authority is unique per transaction (multiple NULLs are allowed).
create unique index if not exists payments_authority on payments (authority);

-- Password + username sign-in (added after the users table already existed in
-- production). Both nullable: OTP-only accounts keep working untouched.
alter table users add column if not exists username text;
alter table users add column if not exists password_hash text;
-- username unique, but many NULLs allowed (unset accounts). Stored lowercased.
create unique index if not exists users_username on users (username);

-- records_habit indexed (data->>'habitId') for a query that was never written:
-- the habit-delete cascade matches the month id prefix (habitId|YYYY-MM), see
-- childMonthIds in services/sync.ts. An unused index is not free; dropped rather
-- than left "just in case". Re-add it WITH the query that uses it if that changes.
drop index if exists records_habit;

insert into plans (id, name_fa, name_en, months, price_toman) values
  ('m1',  'یک‌ماهه', '1 Month',  1,  59000),
  ('m3',  'سه‌ماهه', '3 Months', 3,  149000),
  ('m12', 'یک‌ساله', '1 Year',   12, 449000)
on conflict (id) do nothing;

-- Hourly purge of expired OTP rows (the Node backend did this with setInterval;
-- edge functions have no resident process, so the database does it itself).
-- OTP rows double as the rate-limit ledger, so they must live 24h first.
create extension if not exists pg_cron;
select cron.schedule('routino-otp-purge', '0 * * * *',
  $$delete from otp_codes where created_at < now() - interval '24 hours'$$);
-- Aggregate auth counters are bounded by key/window and expire automatically.
select cron.schedule('routino-auth-rate-limit-purge', '30 * * * *',
  $$delete from auth_rate_limit_buckets where expires_at < now()$$);

-- Re-running setup must replace, not duplicate, the database-local compactor.
select cron.unschedule(jobid) from cron.job where jobname = 'routino-task-month-compaction';
select cron.schedule(
  'routino-task-month-compaction',
  '17 4 * * *',
  $$begin;
set local statement_timeout = '5000ms';
set local lock_timeout = '1000ms';
select * from routino_run_task_month_compaction(now(), 500);
commit;$$
);

-- Tombstones, weekly. A deleted habit or log leaves a row behind on purpose: a
-- delete has to be able to TRAVEL to the user's other devices, and an absence
-- cannot. But it only has to travel once, so a user who tidies up their habits
-- every month should not keep carrying every tombstone forever.
--
-- The two halves must happen together, which is why this is one statement.
-- Raising `users.gc_seq` to the highest seq removed is what makes deleting a
-- tombstone safe: any device whose cursor still sits below that line is told to
-- wipe and resync from zero (`reset: true` in services/sync.ts) instead of
-- being allowed to miss the delete and silently RESURRECT the record. Delete
-- without the bump and a phone left in a drawer for four months comes back with
-- every habit its owner ever threw away.
--
-- 90 days is the promise: a device offline longer than that pays for a full
-- resync, which is correct but not free, so do not shorten this casually.
select cron.schedule('routino-tombstone-purge', '45 3 * * 0', $$
  with doomed as (
    delete from records
     where deleted = true
       -- 86400000::bigint, not a bare 90 * 86400000: that product is 7.7e9, which
       -- overflows int4 and fails the whole job with "integer out of range" —
       -- weekly, quietly, in a cron log nobody reads.
       and updated_at < (extract(epoch from now()) * 1000)::bigint - 90 * 86400000::bigint
    returning user_id, seq
  ), highest as (
    select user_id, max(seq) as top from doomed group by user_id
  )
  update users u set gc_seq = greatest(u.gc_seq, h.top)
    from highest h where u.id = h.user_id
$$);

-- Lock every table out of Supabase's public PostgREST API (see comment in
-- scripts/gen-setup-sql.mjs). No policies are added on purpose: nothing but
-- the edge function's direct Postgres connection should ever touch these rows.
alter table users enable row level security;
alter table records enable row level security;
alter table otp_codes enable row level security;
alter table auth_rate_limit_buckets enable row level security;
alter table plans enable row level security;
alter table discounts enable row level security;
alter table redemptions enable row level security;
alter table payments enable row level security;
alter table grants enable row level security;
alter table entitlements enable row level security;
alter table feedback enable row level security;
