-- Generated by scripts/gen-task-archive-v2-migration.mjs; no data rewrite or cron change.
-- FIRST deploy and verify the API reader supporting BOTH archive v1 and v2.
-- Once this writer is active, never roll back to a v1-only reader.
-- Existing archives stay unchanged. Small new packets retain v1 to avoid
-- crossing below PostgreSQL's default compression threshold; others use v2.
begin;
set local lock_timeout = '1000ms';
set local statement_timeout = '10000ms';
create or replace function routino_expand_task_archive_item(
  p_version jsonb, p_month text, p_item jsonb
)
returns jsonb language plpgsql immutable security invoker
set search_path = public, pg_temp
as $function$
declare
  p jsonb;
begin
  if p_version = '1'::jsonb then return p_item; end if;
  if p_version is distinct from '2'::jsonb then return 'null'::jsonb; end if;
  if jsonb_typeof(p_item) is distinct from 'array' then return 'null'::jsonb; end if;
  if jsonb_array_length(p_item) <> 3 then return 'null'::jsonb; end if;
  p := p_item->2;
  if jsonb_typeof(p) is distinct from 'array' then return 'null'::jsonb; end if;
  if jsonb_array_length(p) <> 6 then return 'null'::jsonb; end if;
  if jsonb_typeof(p->0) is distinct from 'string'
     or (p->>0) !~ '^[0-9]{2}$'
     or jsonb_typeof(p->5) is distinct from 'object' then return 'null'::jsonb; end if;
  if (p->5) - array['note','unitKind','reminderAt','color','icon'] <> '{}'::jsonb
    then return 'null'::jsonb; end if;
  return jsonb_build_array(p_item->0, p_item->1,
    jsonb_build_object('id', p_item->0, 'dateKey', p_month || '-' || (p->>0),
      'title', p->1, 'type', p->2, 'target', p->3, 'value', p->4, 'done', true) || (p->5));
end;
$function$;

-- A short v2 tuple can fall below TOAST's compression threshold while v1 was
-- compressed already, increasing physical storage. Keep those packets as v1.
-- Called on the freshly constructed (uncompressed) JSONB, never a stored datum.
create or replace function routino_task_archive_storage(p_compact jsonb)
returns jsonb language sql immutable strict security invoker
set search_path = public, pg_temp
as $function$
  select case when pg_column_size(p_compact) >= 2048 then p_compact
    else jsonb_set(jsonb_set(p_compact, '{v}', '1'::jsonb), '{items}', (
      select jsonb_agg(routino_expand_task_archive_item('2'::jsonb, p_compact->>'monthKey', item) order by ord)
      from jsonb_array_elements(p_compact->'items') with ordinality as entries(item, ord)
    )) end;
$function$;

create or replace function routino_compact_task_months(
  p_now timestamptz,
  p_max_tasks integer
)
returns table (
  owner_id uuid,
  month_key text,
  archived_tasks integer,
  archive_rows integer
)
language plpgsql
volatile
security invoker
set search_path = public, pg_temp
as $function$
declare
  v_limit integer := greatest(1, least(coalesce(p_max_tasks, 1), 500));
  v_group record;
  v_task record;
  v_chunk integer;
  v_chunk_count integer;
  v_chunk_bytes bigint;
  v_archive_rows integer;
  v_archived_tasks integer;
  v_end_seq bigint;
  v_deleted integer;
begin
  create temp table if not exists routino_compaction_selected (
    user_id uuid not null,
    task_id text not null,
    task_data jsonb not null,
    updated_at bigint not null,
    month_key text not null,
    envelope_bytes integer not null,
    primary key (user_id, task_id)
  ) on commit drop;
  create temp table if not exists routino_compaction_items (
    user_id uuid not null,
    month_key text not null,
    chunk_no integer not null,
    task_id text not null,
    task_data jsonb not null,
    updated_at bigint not null,
    envelope_bytes integer not null,
    primary key (user_id, month_key, chunk_no, task_id)
  ) on commit drop;
  truncate pg_temp.routino_compaction_selected;
  truncate pg_temp.routino_compaction_items;

  -- Claim owners before source tasks. Foreground sync takes this same owner
  -- lock first, so a busy owner is skipped without retaining any task locks.
  with candidate_owners as materialized (
    select source.user_id
      from records source
     where source.kind = 'tasks'
       and source.deleted = false
       and source.data->>'done' = 'true'
       and routino_task_archive_candidate_valid(source.id, source.data)
       and source.updated_at between 0 and 9007199254740991
       and left(source.data->>'dateKey', 7) < to_char(
         (p_now - interval '7 days') at time zone 'UTC', 'YYYY-MM'
       )
       and source.updated_at <= floor(
         extract(epoch from (p_now - interval '7 days')) * 1000
       )::bigint
       and not exists (
         select 1 from records archive
         cross join lateral jsonb_array_elements(
           case when jsonb_typeof(archive.data->'items') = 'array'
             then archive.data->'items' else '[]'::jsonb end
         ) item
          where archive.user_id = source.user_id
            and archive.kind = 'taskMonths'
            and item->>0 = source.id
       )
     group by source.user_id
     order by source.user_id
     limit v_limit
  ),
  locked_owners as materialized (
    select u.id
      from users u
      join candidate_owners candidate on candidate.user_id = u.id
     order by u.id
     for update of u skip locked
  ),
  locked as (
    select source.user_id,
           source.id as task_id,
           source.data as task_data,
           source.updated_at,
           left(source.data->>'dateKey', 7) as month_key,
           octet_length(jsonb_build_object(
             'kind', 'tasks',
             'id', source.id,
             'data', source.data,
             'updatedAt', source.updated_at,
             'deleted', false
           )::text)::integer as envelope_bytes
      from records source
      join locked_owners owner on owner.id = source.user_id
     where source.kind = 'tasks'
       and source.deleted = false
       and source.data->>'done' = 'true'
       and routino_task_archive_candidate_valid(source.id, source.data)
       and source.updated_at between 0 and 9007199254740991
       and left(source.data->>'dateKey', 7) < to_char(
         (p_now - interval '7 days') at time zone 'UTC', 'YYYY-MM'
       )
       and source.updated_at <= floor(
         extract(epoch from (p_now - interval '7 days')) * 1000
       )::bigint
       and not exists (
         select 1
           from records archive
           cross join lateral jsonb_array_elements(
             case when jsonb_typeof(archive.data->'items') = 'array'
               then archive.data->'items' else '[]'::jsonb end
           ) item
          where archive.user_id = source.user_id
            and archive.kind = 'taskMonths'
            and item->>0 = source.id
       )
     order by source.user_id, left(source.data->>'dateKey', 7), source.id collate "C"
     limit v_limit
     for update of source skip locked
  )
  insert into pg_temp.routino_compaction_selected (
    user_id, task_id, task_data, updated_at, month_key, envelope_bytes
  )
  select locked.user_id, locked.task_id, locked.task_data, locked.updated_at,
         locked.month_key, locked.envelope_bytes
    from locked;

  for v_group in
    select selected.user_id, selected.month_key
      from pg_temp.routino_compaction_selected selected
     group by selected.user_id, selected.month_key
     order by selected.user_id, selected.month_key
  loop
    v_chunk := 1;
    v_chunk_count := 0;
    v_chunk_bytes := 0;
    for v_task in
      select selected.*
        from pg_temp.routino_compaction_selected selected
       where selected.user_id = v_group.user_id
         and selected.month_key = v_group.month_key
       order by selected.task_id collate "C"
    loop
      if v_chunk_count > 0 and (
        v_chunk_count >= 32 or v_chunk_bytes + v_task.envelope_bytes > 98304
      ) then
        v_chunk := v_chunk + 1;
        v_chunk_count := 0;
        v_chunk_bytes := 0;
      end if;
      insert into pg_temp.routino_compaction_items (
        user_id, month_key, chunk_no, task_id, task_data, updated_at, envelope_bytes
      ) values (
        v_task.user_id, v_task.month_key, v_chunk, v_task.task_id,
        v_task.task_data, v_task.updated_at, v_task.envelope_bytes
      );
      v_chunk_count := v_chunk_count + 1;
      v_chunk_bytes := v_chunk_bytes + v_task.envelope_bytes;
    end loop;

    select count(*)::integer into v_archive_rows
      from (
        select items.chunk_no
          from pg_temp.routino_compaction_items items
         where items.user_id = v_group.user_id
           and items.month_key = v_group.month_key
         group by items.chunk_no
      ) chunks;
    select count(*)::integer into v_archived_tasks
      from pg_temp.routino_compaction_selected selected
     where selected.user_id = v_group.user_id
       and selected.month_key = v_group.month_key;

    -- Reserve row-cap headroom for the archive inserts. This temporary counter
    -- reservation is invisible before commit and is restored after source
    -- deletion; the existing triggers still account for both physical writes.
    update users u
       set seq = u.seq + v_archive_rows,
           sync_record_count = u.sync_record_count - v_archive_rows
     where u.id = v_group.user_id
    returning u.seq into v_end_seq;

    insert into records (user_id, kind, id, data, updated_at, deleted, seq)
    select v_group.user_id,
           'taskMonths',
           v_group.month_key || '|' || md5(string_agg(items.task_id, E'\n' order by items.task_id collate "C")),
           routino_task_archive_storage(jsonb_build_object(
             'v', 2,
             'monthKey', v_group.month_key,
             'count', count(*)::integer,
             'checksum', md5(string_agg(
               items.task_id || E'\n' || items.updated_at::text || E'\n' || items.task_data::text,
               E'\n' order by items.task_id collate "C"
             )),
             'items', jsonb_agg(
               jsonb_build_array(items.task_id, items.updated_at,
                 jsonb_build_array(right(items.task_data->>'dateKey', 2),
                   items.task_data->'title', items.task_data->'type',
                   items.task_data->'target', items.task_data->'value',
                   items.task_data - array['id','dateKey','title','type','target','value','done']))
               order by items.task_id collate "C"
             )
           )),
           max(items.updated_at),
           false,
           v_end_seq - v_archive_rows + items.chunk_no
      from pg_temp.routino_compaction_items items
     where items.user_id = v_group.user_id
       and items.month_key = v_group.month_key
     group by items.chunk_no
     order by items.chunk_no;

    if exists (
      select 1
        from records archive
        join (
          select items.chunk_no,
                 v_group.month_key || '|' || md5(string_agg(items.task_id, E'\n' order by items.task_id collate "C")) as archive_id,
                 count(*)::integer as item_count,
                 md5(string_agg(
                   items.task_id || E'\n' || items.updated_at::text || E'\n' || items.task_data::text,
                   E'\n' order by items.task_id collate "C"
                 )) as checksum
            from pg_temp.routino_compaction_items items
           where items.user_id = v_group.user_id
             and items.month_key = v_group.month_key
           group by items.chunk_no
        ) expected on expected.archive_id = archive.id
       where archive.user_id = v_group.user_id
         and archive.kind = 'taskMonths'
         and (
           archive.deleted
           or coalesce(archive.data->'v' not in ('1'::jsonb, '2'::jsonb), true)
           or archive.data->>'monthKey' is distinct from v_group.month_key
           or (archive.data->>'count')::integer is distinct from expected.item_count
           or jsonb_array_length(archive.data->'items') is distinct from expected.item_count
           or archive.data->>'checksum' is distinct from expected.checksum
           or (archive.data->>'count')::integer is distinct from jsonb_array_length(archive.data->'items')
           or archive.data->>'checksum' is distinct from (
             select md5(string_agg(
               item->>0 || E'\n' || (item->>1)::bigint::text || E'\n' ||
                 (routino_expand_task_archive_item(archive.data->'v', archive.data->>'monthKey', item)->2)::text,
               E'\n' order by (item->>0) collate "C"
             ))
               from jsonb_array_elements(archive.data->'items') item
           )
         )
    ) then
      raise exception 'task archive verification failed: metadata mismatch';
    end if;

    if exists (
      (
        select selected.task_id, selected.updated_at, selected.task_data
          from pg_temp.routino_compaction_selected selected
         where selected.user_id = v_group.user_id
           and selected.month_key = v_group.month_key
        except
        select item->>0, (item->>1)::bigint,
               routino_expand_task_archive_item(archive.data->'v', archive.data->>'monthKey', item)->2
          from records archive
          join (
            select v_group.month_key || '|' || md5(string_agg(items.task_id, E'\n' order by items.task_id collate "C")) as archive_id
              from pg_temp.routino_compaction_items items
             where items.user_id = v_group.user_id
               and items.month_key = v_group.month_key
             group by items.chunk_no
          ) expected on expected.archive_id = archive.id
          cross join lateral jsonb_array_elements(archive.data->'items') item
         where archive.user_id = v_group.user_id and archive.kind = 'taskMonths'
      )
      union all
      (
        select item->>0, (item->>1)::bigint,
               routino_expand_task_archive_item(archive.data->'v', archive.data->>'monthKey', item)->2
          from records archive
          join (
            select v_group.month_key || '|' || md5(string_agg(items.task_id, E'\n' order by items.task_id collate "C")) as archive_id
              from pg_temp.routino_compaction_items items
             where items.user_id = v_group.user_id
               and items.month_key = v_group.month_key
             group by items.chunk_no
          ) expected on expected.archive_id = archive.id
          cross join lateral jsonb_array_elements(archive.data->'items') item
         where archive.user_id = v_group.user_id and archive.kind = 'taskMonths'
        except
        select selected.task_id, selected.updated_at, selected.task_data
          from pg_temp.routino_compaction_selected selected
         where selected.user_id = v_group.user_id
           and selected.month_key = v_group.month_key
      )
    ) then
      raise exception 'task archive verification failed: source mismatch';
    end if;

    delete from records source
     using pg_temp.routino_compaction_selected selected
     where selected.user_id = v_group.user_id
       and selected.month_key = v_group.month_key
       and source.user_id = selected.user_id
       and source.kind = 'tasks'
       and source.id = selected.task_id
       and source.updated_at = selected.updated_at
       and source.data = selected.task_data
       and source.deleted = false;
    get diagnostics v_deleted = row_count;
    if v_deleted <> v_archived_tasks then
      raise exception 'task archive verification failed: delete mismatch';
    end if;

    update users u
       set sync_record_count = u.sync_record_count + v_archive_rows
     where u.id = v_group.user_id;

    owner_id := v_group.user_id;
    month_key := v_group.month_key;
    archived_tasks := v_archived_tasks;
    archive_rows := v_archive_rows;
    return next;
  end loop;
end
$function$;


revoke execute on function routino_compact_task_months(timestamptz, integer) from public;
commit;
