/**
 * Admin API — thin edge adapter. All queries live in shared/services/admin.ts
 * (byte-identical to the backend copy). The owner signs in with an
 * admin-namespaced OTP and receives a signed HttpOnly cookie.
 */
import { Hono } from "hono";
import type { Context, Next } from "hono";
import { z } from "zod";
import { clientIp, readJson, type AppEnv, type Deps } from "../deps.ts";
import { normalizePhone } from "../shared/lib/phone.ts";
import { forbidden, tooMany, unauthorized } from "../shared/lib/http-errors.ts";
import { SmsNotSentError } from "../shared/providers/sms/index.ts";
import {
  ADMIN_CSRF_COOKIE,
  ADMIN_SESSION_COOKIE,
  adminCsrfMatches,
  adminOtpLedgerKey,
  adminPhoneMatches,
  adminSessionCookie,
  clearAdminCsrfCookie,
  clearAdminSessionCookie,
  csrfCookie,
  issueAdminSession,
  newAdminCsrfToken,
  readCookie,
  verifyAdminSession,
} from "../shared/services/admin-auth.ts";
import { adminDeleteUser } from "../shared/services/admin-user-delete.ts";
import { claimAdminOtpRequest } from "../shared/services/login-throttle.ts";
import { claimSendSlot, releaseSendSlot, verifyCode } from "../shared/services/otp.ts";
import {
  adminCreateDiscount,
  adminGrant,
  adminListDiscounts,
  adminListPayments,
  adminListPlans,
  adminListUsers,
  adminOverview,
  adminSetPassword,
  adminUpdateDiscount,
  adminUpdatePlanPrice,
  adminUserDetail,
} from "../shared/services/admin.ts";

const adminOtpRequestBody = z.object({ phone: z.string().min(1).max(32) });
const adminOtpVerifyBody = z.object({
  phone: z.string().min(1).max(32),
  code: z.string().min(4).max(8),
});

// Negatives allowed — see the Fastify twin in backend/src/routes/admin.ts for
// why. This file is hand-maintained, NOT generated by `npm run sync:edge`, so a
// change there does not reach production until it is mirrored here.
const grantBody = z.object({
  months: z.number().int().min(-36).max(36).default(0),
  days: z.number().int().min(-366).max(366).default(0),
  planId: z.string().min(1).max(32).default("admin"),
  note: z.string().max(500).optional(),
});

const setPasswordBody = z.object({
  phone: z.string().min(1).max(32),
  password: z.string().min(1).max(128),
});

const deleteUserBody = z.object({
  confirmation: z.string().min(1).max(64),
});

const discountCreateBody = z.object({
  code: z
    .string()
    .min(3)
    .max(32)
    .regex(/^[A-Za-z0-9_-]+$/, "letters/digits/dash only"),
  percent: z.number().int().min(1).max(100),
  maxUses: z.number().int().min(1).max(1_000_000).nullable().optional(),
  expiresAt: z.number().int().positive().nullable().optional(), // epoch ms
  phone: z.string().max(20).nullable().optional(),
});

const discountUpdateBody = z.object({
  active: z.boolean().optional(),
  maxUses: z.number().int().min(1).max(1_000_000).nullable().optional(),
  expiresAt: z.number().int().positive().nullable().optional(),
});

const planPriceBody = z.object({
  priceToman: z.number().int().min(1_000).max(1_000_000_000),
});

export function adminRoutes(deps: Deps) {
  const { db, env, sms } = deps;
  const now = () => new Date(deps.now());

  const appendCookie = (c: Context<AppEnv>, value: string) => {
    c.header("Set-Cookie", value, { append: true });
  };

  const setSessionCookies = async (c: Context<AppEnv>, t: Date) => {
    const session = await issueAdminSession(env, t);
    const csrf = newAdminCsrfToken();
    appendCookie(c, adminSessionCookie(session.token, session.expiresAt));
    appendCookie(c, csrfCookie(csrf, session.expiresAt));
  };

  const clearCookies = (c: Context<AppEnv>) => {
    appendCookie(c, clearAdminSessionCookie());
    appendCookie(c, clearAdminCsrfCookie());
  };

  const requireSession = async (c: Context<AppEnv>) => {
    const t = now();
    const token = readCookie(c.req.header("cookie"), ADMIN_SESSION_COOKIE);
    if (!token) throw unauthorized("invalid_admin_session", "Admin session is required");
    try {
      const session = await verifyAdminSession(env, token, t);
      if (session.renew) await setSessionCookies(c, t);
    } catch (error) {
      clearCookies(c);
      throw error;
    }
  };

  const requireAdmin = async (c: Context<AppEnv>, next: Next) => {
    await requireSession(c);
    if (c.req.method === "POST") {
      const csrf = readCookie(c.req.header("cookie"), ADMIN_CSRF_COOKIE);
      if (!adminCsrfMatches(csrf, c.req.header("x-admin-csrf"))) {
        throw forbidden("bad_admin_csrf", "Admin CSRF token is invalid");
      }
    }
    await next();
  };

  const r = new Hono<AppEnv>();

  r.post("/admin/auth/otp/request", async (c) => {
    const { phone } = adminOtpRequestBody.parse(await readJson(c));
    const t = now();
    const ip = clientIp(c, env);
    const verdict = await claimAdminOtpRequest(db, env, ip, t);
    if (!verdict.ok) {
      throw tooMany("Too many admin code requests. Try again later.", verdict.retryAfter);
    }

    if (adminPhoneMatches(env, phone)) {
      const slot = await claimSendSlot(db, env, adminOtpLedgerKey(env), ip, t);
      if (slot) {
        try {
          await sms.sendOtp(normalizePhone(env.ADMIN_PHONE)!, slot.code);
        } catch (error) {
          if (error instanceof SmsNotSentError) await releaseSendSlot(db, slot.slotId);
          console.error("admin otp send failed", {
            error:
              error instanceof Error ? { name: error.name, message: error.message } : undefined,
          });
        }
      }
    }
    return c.json({ accepted: true }, 202);
  });

  r.post("/admin/auth/otp/verify", async (c) => {
    const { phone, code } = adminOtpVerifyBody.parse(await readJson(c));
    if (!adminPhoneMatches(env, phone)) {
      throw unauthorized("bad_admin_code", "The code is wrong or has expired");
    }
    const result = await verifyCode(db, env, adminOtpLedgerKey(env), code, now());
    if (!result.ok) {
      if (result.reason === "too_many")
        throw tooMany("Too many wrong attempts. Request a new code.");
      throw unauthorized("bad_admin_code", "The code is wrong or has expired");
    }
    await setSessionCookies(c, now());
    return c.json({ authenticated: true });
  });

  r.get("/admin/auth/session", async (c) => {
    await requireSession(c);
    return c.json({ authenticated: true });
  });

  r.post("/admin/auth/logout", (c) => {
    clearCookies(c);
    return c.body(null, 204);
  });

  // Authentication endpoints above stay public; only the data surface below
  // uses the session/CSRF guard.
  r.use("/admin/*", requireAdmin);

  r.get("/admin/overview", async (c) => c.json(await adminOverview(db, now())));

  r.get("/admin/users", async (c) => {
    const users = await adminListUsers(
      db,
      { q: c.req.query("q"), limit: Number(c.req.query("limit")) || undefined },
      now(),
    );
    return c.json({ users });
  });

  r.get("/admin/users/:id", async (c) =>
    c.json(await adminUserDetail(db, c.req.param("id"), now())),
  );

  r.post("/admin/users/:id/grant", async (c) => {
    const body = grantBody.parse(await readJson(c));
    const res = await adminGrant(db, c.req.param("id"), body, now());
    console.info("admin grant", {
      userId: c.req.param("id"),
      months: body.months,
      days: body.days,
    });
    return c.json(res);
  });

  r.post("/admin/users/:id/delete", async (c) => {
    const id = c.req.param("id");
    const { confirmation } = deleteUserBody.parse(await readJson(c));
    const res = await adminDeleteUser(db, env, id, confirmation);
    console.warn("admin permanently deleted user", { userId: id });
    return c.json(res);
  });

  // Fixed path, so it never collides with `/admin/users/:id`.
  r.post("/admin/users/set-password", async (c) => {
    const body = setPasswordBody.parse(await readJson(c));
    const res = await adminSetPassword(db, body, now());
    console.info("admin set password", { created: res.created });
    return c.json(res);
  });

  r.get("/admin/payments", async (c) => {
    const payments = await adminListPayments(db, {
      status: c.req.query("status"),
      limit: Number(c.req.query("limit")) || undefined,
    });
    return c.json({ payments });
  });

  r.get("/admin/plans", async (c) => c.json({ plans: await adminListPlans(db) }));

  r.post("/admin/plans/:id", async (c) => {
    const body = planPriceBody.parse(await readJson(c));
    return c.json(await adminUpdatePlanPrice(db, c.req.param("id"), body.priceToman));
  });

  r.get("/admin/discounts", async (c) => c.json({ discounts: await adminListDiscounts(db) }));

  r.post("/admin/discounts", async (c) =>
    c.json(await adminCreateDiscount(db, discountCreateBody.parse(await readJson(c)))),
  );

  r.post("/admin/discounts/:code", async (c) =>
    c.json(
      await adminUpdateDiscount(
        db,
        c.req.param("code"),
        discountUpdateBody.parse(await readJson(c)),
      ),
    ),
  );

  return r;
}
