/** Delta sync routes — thin edge adapter mirroring backend/src/routes/sync.ts.
 *
 * All the logic lives in `shared/services/sync.ts` (generated by
 * `npm run sync:edge`), so this file is just the Hono binding. Deliberately not
 * entitlement-gated: see the backend file for why sync is an auth boundary and
 * not a paywall. */
import { Hono } from "hono";
import { z } from "zod";
import { makeAuthenticate, readJson, requireUser, type AppEnv, type Deps } from "../deps.ts";
import { readEntitlement } from "../shared/services/entitlement.ts";
import { settleOpenPayments } from "../shared/services/payment-flow.ts";
import { touchUserActivity } from "../shared/services/user-activity.ts";
import {
  MAX_PUSH_RECORDS,
  PULL_PAGE_SIZE,
  exchangeRecords,
  pullRecords,
  pushRecords,
  type PushRecord,
} from "../shared/services/sync.ts";

const pushBody = z.object({
  records: z
    .array(
      z.object({
        kind: z.string().min(1).max(32),
        id: z.string().min(1).max(128),
        data: z.unknown(),
        updatedAt: z.number().int().nonnegative(),
        deleted: z.boolean(),
      }),
    )
    .max(MAX_PUSH_RECORDS),
});

const pullQuery = z.object({
  cursor: z.coerce.number().int().nonnegative().default(0),
  limit: z.coerce.number().int().positive().max(PULL_PAGE_SIZE).default(PULL_PAGE_SIZE),
});

const exchangeBody = pushBody.extend({
  protocolVersion: z.literal(2),
  cursor: z.number().int().nonnegative().default(0),
  limit: z.number().int().positive().max(PULL_PAGE_SIZE).default(PULL_PAGE_SIZE),
  includeAccountState: z.boolean().default(false),
});

export function syncRoutes(deps: Deps) {
  const { db, psp } = deps;
  const now = () => new Date(deps.now());
  const auth = makeAuthenticate(deps);
  const r = new Hono<AppEnv>();

  r.post("/sync/exchange", auth, async (c) => {
    const user = requireUser(c);
    const input = exchangeBody.parse(await readJson(c));
    const t = now();
    const page = await exchangeRecords(
      db,
      user.id,
      input.cursor,
      input.records as PushRecord[],
      t,
      input.limit,
    );
    await touchUserActivity(db, user.id, t);
    if (!input.includeAccountState || page.hasMore || page.reset) return c.json(page);
    await settleOpenPayments(db, psp, user.id, t);
    return c.json({ ...page, entitlement: await readEntitlement(db, user.id, t) });
  });

  r.post("/sync/push", auth, async (c) => {
    const user = requireUser(c);
    const { records } = pushBody.parse(await readJson(c));
    return c.json(await pushRecords(db, user.id, records as PushRecord[], now()));
  });

  // The last page carries the entitlement too, so the app does not make a
  // separate `GET /subscriptions/me` request every time it opens. See the
  // Fastify twin for the reasoning.
  r.get("/sync/pull", auth, async (c) => {
    const user = requireUser(c);
    const { cursor, limit } = pullQuery.parse({
      cursor: c.req.query("cursor"),
      limit: c.req.query("limit"),
    });
    const page = await pullRecords(db, user.id, cursor, limit);
    if (page.hasMore) return c.json(page);
    // Finish any payment whose gateway callback never made it back — see the
    // Fastify twin. A VPN-routed browser drops that redirect often enough that
    // without this the money moves and nothing is granted.
    await settleOpenPayments(db, psp, user.id, now());
    return c.json({ ...page, entitlement: await readEntitlement(db, user.id, now()) });
  });

  return r;
}
